<a href="https://colab.research.google.com/github/eshwarjyEnder-Cyber/Ender/blob/main/Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
empty_array = np.array(object = [])

In [ ]:
type(empty_array)

numpy.ndarray

In [ ]:
my_array = np.array([1,2,3])

In [ ]:
my_array.dtype

dtype('int64')

In [ ]:
my_array = np.array([[[1.5,2,3.5,4]]])

In [ ]:
my_array.dtype

dtype('float64')

In [ ]:
np.array(range(1, 10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.zeros(shape = 10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(shape = 5, dtype = 'int')

array([0, 0, 0, 0, 0])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.linspace(start = 1, stop = 15, num = 10)

array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ])

In [ ]:
np.array([[1,2,3], [4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import numpy as np

In [ ]:
ages = np.array([18, 15, 23, 14, 20])

In [ ]:
ages >= 18

array([ True, False,  True, False,  True])

In [ ]:
ages[ages >= 18]

array([18, 23, 20])

In [ ]:
ages[[4,0,1]]

array([20, 18, 15])

In [ ]:
ages

array([18, 15, 23, 14, 20])

In [ ]:
np.where(ages % 2 ==0)

(array([0, 3, 4]),)

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
matrix[1][2]

np.int64(6)

In [ ]:
matrix[1, 2]

np.int64(6)

In [ ]:
matrix[matrix > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr= np.array([1,2,3,4,5,6])

In [ ]:
arr = np.append(arr = arr, values=7)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])

In [ ]:
np.concatenate([arr1,arr2,arr3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6]])
mat3 = np.array([[7], [8]])

In [ ]:
np.concatenate((mat1, mat2), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((mat1, mat3), axis = 1)

array([[1, 2, 7],
       [3, 4, 8]])

In [ ]:
# Reshaping array
arr = np.array(['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy'])

In [ ]:
np.reshape(a = arr, newshape = (2, 3))

array([['Ashok', 'Ravi', 'Kumar'],
       ['Shiela', 'P.', 'Reddy']], dtype='<U6')

In [ ]:
np.reshape(arr, (1,1,6))

array([[['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy']]], dtype='<U6')

In [ ]:
np.reshape(arr, (-1, 3))

array([['Ashok', 'Ravi', 'Kumar'],
       ['Shiela', 'P.', 'Reddy']], dtype='<U6')

In [ ]:
mat = np.transpose([['Apple', 'Bread', 'Banana'],['Rs.120', 'Rs.20', 'Rs.50']])

In [ ]:
mat

array([['Apple', 'Rs.120'],
       ['Bread', 'Rs.20'],
       ['Banana', 'Rs.50']], dtype='<U6')

In [ ]:
mat.transpose()

array([['Apple', 'Bread', 'Banana'],
       ['Rs.120', 'Rs.20', 'Rs.50']], dtype='<U6')

In [ ]:
mat.ravel()

array(['Apple', 'Rs.120', 'Bread', 'Rs.20', 'Banana', 'Rs.50'],
      dtype='<U6')

In [ ]:
mat.transpose()

array([['Apple', 'Bread', 'Banana'],
       ['Rs.120', 'Rs.20', 'Rs.50']], dtype='<U6')

In [ ]:
mat.transpose().ravel()

array(['Apple', 'Bread', 'Banana', 'Rs.120', 'Rs.20', 'Rs.50'],
      dtype='<U6')

In [ ]:
mat.transpose()

array([['Apple', 'Bread', 'Banana'],
       ['Rs.120', 'Rs.20', 'Rs.50']], dtype='<U6')

In [ ]:
mat.flatten()

array(['Apple', 'Rs.120', 'Bread', 'Rs.20', 'Banana', 'Rs.50'],
      dtype='<U6')

In [ ]:
mat.transpose()

array([['Apple', 'Bread', 'Banana'],
       ['Rs.120', 'Rs.20', 'Rs.50']], dtype='<U6')

In [ ]:
import numpy as np


In [ ]:
mat = np.array([[10,20,30],[40,50,60]])

In [ ]:
mat + np.array([1,2,3])

array([[11, 22, 33],
       [41, 52, 63]])

In [ ]:
import pandas as pd

In [ ]:
empty_series = pd.Series()

In [ ]:
empty_series

,0


In [ ]:
name_series = pd.Series(data = ['Ashok', 'Kumar', 18, 183], index= [' Forename', 'Surname', 'Age', 'Hight'], name = 'Studnet info')

In [ ]:
name_series

,Studnet info
Forename,Ashok
Surname,Kumar
Age,18
Hight,183


In [ ]:
name_series.dtype

dtype('O')

In [ ]:
name_series.ndim

1

In [ ]:
name_series.shape


(4,)

In [ ]:
name_series.index

Index([' Forename', 'Surname', 'Age', 'Hight'], dtype='object')

In [ ]:
name_series.values

array(['Ashok', 'Kumar', 18, 183], dtype=object)

In [ ]:
name_series.name

'Studnet info'

In [ ]:
my_series = pd.Series({'A': 1, 'B': 2, 'C': 3, 'D': 4})

In [ ]:
my_series

,0
A,1
B,2
C,3
D,4


In [ ]:
my_series.ndim

1

In [ ]:
my_series.dtype

dtype('int64')

In [ ]:
my_series = pd.Series(data = [32, 33 , 30, 29, 36], index = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], name = 'Peak Temperature')

In [ ]:
my_series

,Peak Temperature
Mon,32
Tue,33
Wed,30
Thu,29
Fri,36


In [ ]:
my_series.iloc[0]

np.int64(32)

In [ ]:
my_series['Tue']

np.int64(33)

In [ ]:
my_series.iloc[1:3]

,Peak Temperature
Tue,33
Wed,30


In [ ]:
my_series.iloc[::-1]

,Peak Temperature
Fri,36
Thu,29
Wed,30
Tue,33
Mon,32


In [ ]:
my_series['Tue':'Fri']

,Peak Temperature
Tue,33
Wed,30
Thu,29
Fri,36


In [ ]:
sorted_series = my_series.sort_values()

In [ ]:
sorted_series

,Peak Temperature
Thu,29
Wed,30
Mon,32
Tue,33
Fri,36


In [ ]:
my_series.loc[my_series >= 30]

,Peak Temperature
Mon,32
Tue,33
Wed,30
Fri,36


In [ ]:
my_series.loc[my_series.isin([29, 28, 30])]

,Peak Temperature
Wed,30
Thu,29


In [ ]:
my_series.iloc[[0,0,4,2]]

,Peak Temperature
Mon,32
Mon,32
Fri,36
Wed,30


In [ ]:
my_series[['Mon', 'Wed', 'Fri', 'Fri']]

,Peak Temperature
Mon,32
Wed,30
Fri,36
Fri,36


In [ ]:
import pandas as pd

In [ ]:
phone_steps = pd.Series(data = [6000, 7400, 6750, 8000, 5500], index = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], name = 'Phone')
smartwatch_steps = pd.Series(data = [5500, 4750, 6250], index = ['Mon', 'Wed', 'Fri'], name = 'Smart Watch')



In [ ]:
phone_steps + smartwatch_steps

,0
Fri,11750.0
Mon,11500.0
Thu,NaN
Tue,NaN
Wed,11500.0


In [ ]:
phone_steps.add(smartwatch_steps, fill_value= 0)

,0
Fri,11750.0
Mon,11500.0
Thu,8000.0
Tue,7400.0
Wed,11500.0


In [ ]:
monthly_expences_in_dollars = pd.Series(data = [700, 550, 480, 625, 670, 515], index = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'])

In [ ]:
monthly_expences_in_dollars

,0
Jan,700
Feb,550
Mar,480
Apr,625
May,670
Jun,515


In [ ]:
monthly_expences_in_dollars.mul(84).sort_values(ascending= False)

,0
Jan,58800
May,56280
Apr,52500
Feb,46200
Jun,43260
Mar,40320


In [ ]:
companies = pd.Series(['Meta ', 'Ama!on ', '#Apple', '#Netflix', 'Google ', 'CORRUPT'])


In [ ]:
companies

,0
0,Meta
1,Ama!on
2,#Apple
3,#Netflix
4,Google
5,CORRUPT


In [ ]:
companies.str.contains('!')

,0
0,False
1,True
2,False
3,False
4,False
5,False


In [ ]:
dates = pd.Series(['2024-01-01', '2024-02-15', '2024-03-30'])
datetime_series = pd.to_datetime(dates)

In [ ]:
datetime_series

,0
0,2024-01-01
1,2024-02-15
2,2024-03-30


In [ ]:
datetime_series.dt.year

,0
0,2024
1,2024
2,2024


In [ ]:
datetime_series.dt.day

,0
0,1
1,15
2,30


In [ ]:
datetime_series.dt.weekday

,0
0,0
1,3
2,5


In [ ]:
import pandas as pd

s = pd.Series([1, 2, 3, None, 5])
s.isna()

,0
0,False
1,False
2,False
3,True
4,False


In [ ]:
import numpy as np
number = [8, 9, 9, 1, 6, 9, 5, 7, 3, 9, 7, 3, 4, 8, 3, 5, 8, 4, 8, 7, 5, 7,
3, 6, 1, 2, 7, 4, 7, 7, 8, 4, 3, 4, 2, 2, 2, 7, 3, 5, 6, 1, 1, 3,
2, 1, 1, 7, 7, 1, 4, 4, 5, 6, 1, 2, 7, 4, 5, 8, 1, 4, 8, 6, 2, 4,
3, 7, 3, 6, 2, 3, 3, 3, 2, 4, 6, 8, 9, 3, 9, 3, 1, 8, 6, 6, 3, 3,
9, 4, 6, 4, 9, 6, 7, 1, 2, 8, 7, 8, 1, 4]
price = [195, 225, 150, 150, 90, 60, 75, 255, 270, 225, 135, 195, 30, 15,
210, 105, 15, 30, 180, 60, 165, 60, 45, 225, 180, 90, 30, 210, 150,
15, 270, 60, 210, 180, 60, 225, 150, 150, 120, 195, 75, 240, 60,
45, 30, 180, 240, 285, 135, 165, 180, 240, 60, 105, 165, 240, 120,
45, 120, 165, 285, 225, 90, 105, 225, 45, 45, 45, 75, 180, 90, 240,
30, 30, 60, 135, 180, 15, 255, 180, 270, 135, 105, 135, 210, 180,
135, 195, 225, 75, 225, 15, 240, 60, 15, 180, 255, 90, 15, 150,
230, 150]

In [ ]:
total_products = len(number)
print(total_products)

102


In [ ]:
total_itmes = sum(number)

In [ ]:
print(total_itmes)

490


In [ ]:
num_array = np.array(number)
total_itmes = np.sum(num_array)

In [ ]:
print(total_itmes)

490


In [ ]:
num_arr = np.array(number)

# Total items sold
total_items = np.sum(num_arr)
print(total_items)

490


In [ ]:
price_arr = np.array(price)

average_price = np.mean(price_arr)

In [ ]:
print(average_price)

139.01960784313727


In [ ]:
price_arr = np.array(price)

# Average price
avg_price = np.mean(price_arr)
print(avg_price)

139.01960784313727


In [ ]:
costliest_item = np.max(price_arr)

In [ ]:
print(costliest_item)

285


In [ ]:
revenue_per_product = num_arr * price
total_revenue = np.sum(revenue_per_product)
print(total_revenue)

67100


In [ ]:
demand_20th = number[19]
demand_50th = number[49]
print(demand_20th, demand_50th, demand_20th > demand_50th)

7 1 True


In [ ]:
price_arr = np.array(price)

avg_price = np.mean(price_arr)
expensive_count = np.sum(price_arr > avg_price)

print(expensive_count)

52


In [ ]:
import numpy as np


In [ ]:
player = [
1
,
2
,
3
,
4
,
5
,
6
,
7
,
8
,
9
,
10
,
11
,
12
,
13
,
14
,
15
,
16
,
17
,
18
,
19
,
20
,
21
,
22
,
23
,
24
,
25
,
26
,
27
,
28
,
29
,
30
,
31
,
32
,
33
,
34
,
35
,
36
,
37
,
38
,
39
,
40
,
41
,
42
,
43
,
44
,
45
,
46
,
47
,
48
,
49
,
50
,
51
,
52
,
53
,
54
,
55
,
56
,
57
,
58
,
59
,
60
,
61
,
62
,
63
,
64
,
65
,
66
,
67
,
68
,
69
,
70
,
71
,
72
,
73
,
74
,
75
,
76
,
77
,
78
,
79
,
80
,
81
,
82
,
83
,
84
,
85
,
86
,
87
,
88
,
89
,
90
,
91
,
92
,
93
,
94
,
95
,
96
,
97
,
98
,
99
,
100
,
101
,
102
,
103
,
104
,
105
,
106
,
107
,
108
,
109
,
110
,
111
,
112
,
113
,
114
,
115
,
116
,
117
,
118
,
119
,
120
,
121
,
122
,
123
,
124
,
125
,
126
,
127
,
128
,
129
,
130
,
131
,
132
,
133
,
134
,
135
,
136
,
137
,
138
,
139
,
140
,
141
,
142
,
143
,
144
,
145
,
146
,
147
,
148
,
149
,
150
,
151
,
152
,
153
,
154
,
155
,
156
,
157
,
158
,
159
,
160
,
161
,
162
,
163
,
164
,
165
,
166
,
167
,
168
,
169
,
170
,
171
,
172
,
173
,
174
,
175
,
176
,
177
,
178
,
179
,
180
,
181
,
182
,
183
,
184
,
185
,
186
,
187
,
188
,
189
,
190
,
191
,
192
,
193
,
194
,
195
,
196
,
197
,
198
,
199
,
200
,
201
,
202
,
203
,
204
,
205
,
206
,
207
,
208
,
209
,
210
,
211
,
212
,
213
,
214
,
215
,
216
,
217
,
218
,
219
,
220
,
221
,
222
,
223
,
224
,
225
,
226
,
227
,
228
,
229
,
230
,
231
,
232
,
233
,
234
,
235
,
236
,
237
,
238
,
239
,
240
,
241
,
242
,
243
,
244
,
245
,
246
,
247
,
248
,
249
,
250
,
251
,
252
,
253
,
254
,
255
,
256
,
257
,
258
,
259
,
260
,
261
,
262
,
263
,
264
,
265
,
266
,
267
,
268
,
269
,
270
,
271
,
272
,
273
,
274
,
275
,
276
,
277
,
278
,
279
,
280
,
281
,
282
,
283
,
284
,
285
,
286
,
287
,
288
,
289
,
290
,
291
,
292
,
293
,
294
,
295
,
296
,
297
,
298
,
299
,
300
,
301
,
302
,
303
,
304
,
305
,
306
,
307
,
308
,
309
,
310
,
311
,
312
,
313
,
314
,
315
,
316
,
317
,
318
,
319
,
320
,
321
,
322
,
323
,
324
,
325
,
326
,
327
,
328
,
329
,
330
,
331
,
332
,
333
,
334
,
335
,
336
,
337
,
338
,
339
,
340
,
341
,
342
,
343
,
344
,
345
,
346
,
347
,
348
,
349
,
350
,
351
,
352
,
353
,
354
,
355
,
356
,
357
,
358
,
359
,
360
,
361
,
362
,
363
,
364
,
365
,
366
,
367
,
368
,
369
,
370
,
371
,
372
,
373
,
374
,
375
,
376
,
377
,
378
,
379
,
380
,
381
,
382
,
383
,
384
,
385
,
386
,
387
,
388
,
389
,
390
,
391
,
392
,
393
,
394
,
395
,
396
,
397
,
398
,
399
,
400
,
401
,
402
,
403
,
404
,
405
,
406
,
407
,
408
,
409
,
410
,
411
,
412
,
413
,
414
,
415
,
416
,
417
,
418
,
419
,
420
,
421
,
422
,
423
,
424
,
425
,
426
,
427
,
428
,
429
,
430
,
431
,
432
,
433
,
434
,
435
,
436
,
437
,
438
,
439
,
440
,
441
,
442
,
443
,
444
,
445
,
446
,
447
,
448
,
449
,
450
,
451
,
452
,
453
,
454
,
455
,
456
,
457
,
458
,
459
,
460
,
461
,
462
,
463
,
464
,
465
,
466
,
467
,
468
,
469
,
470
,
471
,
472
,
473
,
474
,
475
,
476
,
477
,
478
,
479
,
480
,
481
,
482
,
483
,
484
,
485
,
486
,
487
,
488
,
489
,
490
,
491
,
492
,
493
,
494
,
495
,
496
,
497
,
498
,
499
,
500
,
501
,
502
,
503
,
504
,
505
,
506
,
507
,
508
,
509
,
510
,
511
,
512
,
513
,
514
,
515
,
516
,
517
,
518
,
519
,
520
,
521
,
522
,
523
,
524
,
525
,
526
,
527
,
528
,
529
,
530
,
531
,
532
,
533
,
534
,
535
,
536
,
537
,
538
,
539
,
540
,
541
,
542
,
543
,
544
,
545
,
546
,
547
,
548
,
549
,
550
,
551
,
552
,
553
,
554
,
555
,
556
,
557
,
558
,
559
,
560
,
561
,
562
,
563
,
564
,
565
,
566
,
567
,
568
,
569
,
570
,
571
,
572
,
573
,
574
,
575
,
576
,
577
,
578
,
579
,
580
,
581
,
582
,
583
,
584
,
585
,
586
,
587
,
588
,
589
,
590
,
591
,
592
,
593
,
594
,
595
,
596
,
597
,
598
,
599
,
600
,
601
,
602
,
603
,
604
,
605
,
606
,
607
,
608
,
609
,
610
,
611
,
612
,
613
,
614
,
615
,
616
,
617
,
618
,
619
,
620
,
621
,
622
,
623
,
624
,
625
,
626
,
627
,
628
,
629
,
630
,
631
,
632
,
633
,
634
,
635
,
636
,
637
,
638
,
639
,
640
,
641
,
642
,
643
,
644
,
645
,
646
,
647
,
648
,
649
,
650
,
651
,
652
,
653
,
654
,
655
,
656
,
657
,
658
,
659
,
660
,
661
,
662
,
663
,
664
,
665
,
666
,
667
,
668
,
669
,
670
,
671
,
672
,
673
,
674
,
675
,
676
,
677
,
678
,
679
,
680
,
681
,
682
,
683
,
684
,
685
,
686
,
687
,
688
,
689
,
690
,
691
,
692
,
693
,
694
,
695
,
696
,
697
,
698
,
699
,
700
,
701
,
702
,
703
,
704
,
705
,
706
,
707
,
708
,
709
,
710
,
711
,
712
,
713
,
714
,
715
,
716
,
717
,
718
,
719
,
720
,
721
,
722
,
723
,
724
,
725
,
726
,
727
,
728
,
729
,
730
,
731
,
732
,
733
,
734
,
735
,
736
,
737
,
738
,
739
,
740
,
741
,
742
,
743
,
744
,
745
,
746
,
747
,
748
,
749
,
750
,
751
,
752
,
753
,
754
,
755
,
756
,
757
,
758
,
759
,
760
,
761
,
762
,
763
,
764
,
765
,
766
,
767
,
768
,
769
,
770
,
771
,
772
,
773
,
774
,
775
,
776
,
777
,
778
,
779
,
780
,
781
,
782
,
783
,
784
,
785
,
786
,
787
,
788
,
789
,
790
,
791
,
792
,
793
,
794
,
795
,
796
,
797
,
798
,
799
,
800
,
801
,
802
,
803
,
804
,
805
,
806
,
807
,
808
,
809
,
810
,
811
,
812
,
813
,
814
,
815
,
816
,
817
,
818
,
819
,
820
,
821
,
822
,
823
,
824
,
825
,
826
,
827
,
828
,
829
,
830
,
831
,
832
,
833
,
834
,
835
,
836
,
837
,
838
,
839
,
840
,
841
,
842
,
843
,
844
,
845
,
846
,
847
,
848
,
849
,
850
,
851
,
852
,
853
,
854
,
855
,
856
,
857
,
858
,
859
,
860
,
861
,
862
,
863
,
864
,
865
,
866
,
867
,
868
,
869
,
870
,
871
,
872
,
873
,
874
,
875
,
876
,
877
,
878
,
879
,
880
,
881
,
882
,
883
,
884
,
885
,
886
,
887
,
888
,
889
,
890
,
891
,
892
,
893
,
894
,
895
,
896
,
897
,
898
,
899
,
900
,
901
,
902
,
903
,
904
,
905
,
906
,
907
,
908
,
909
,
910
,
911
,
912
,
913
,
914
,
915
,
916
,
917
,
918
,
919
,
920
,
921
,
922
,
923
,
924
,
925
,
926
,
927
,
928
,
929
,
930
,
931
,
932
,
933
,
934
,
935
,
936
,
937
,
938
,
939
,
940
,
941
,
942
,
943
,
944
,
945
,
946
,
947
,
948
,
949
,
950
,
951
,
952
,
953
,
954
,
955
,
956
,
957
,
958
,
959
,
960
,
961
,
962
,
963
,
964
,
965
,
966
,
967
,
968
,
969
,
970
,
971
,
972
,
973
,
974
,
975
,
976
,
977
,
978
,
979
,
980
,
981
,
982
,
983
,
984
,
985
,
986
,
987
,
988
,
989
,
990
,
991
,
992
,
993
,
994
,
995
,
996
,
997
,
998
,
999
,
1000
,
1001
,
1002
,
1003
,
1004
,
1005
,
1006
,
1007
,
1008
,
1009
,
1010
,
1011
,
1012
,
1013
,
1014
,
1015
,
1016
,
1017
,
1018
,
1019
,
1020
,
1021
,
1022
,
1023
,
1024
,
1025
,
1026
,
1027
,
1028
,
1029
,
1030
,
1031
,
1032
,
1033
,
1034
,
1035
,
1036
,
1037
,
1038
,
1039
,
1040
,
1041
,
1042
,
1043
,
1044
,
1045
,
1046
,
1047
,
1048
,
1049
,
1050
,
1051
,
1052
,
1053
,
1054
,
1055
,
1056
,
1057
,
1058
,
1059
,
1060
,
1061
,
1062
,
1063
,
1064
,
1065
,
1066
,
1067
,
1068
,
1069
,
1070
,
1071
,
1072
,
1073
,
1074
,
1075
,
1076
,
1077
,
1078
,
1079
,
1080
,
1081
,
1082
,
1083
,
1084
,
1085
,
1086
,
1087
,
1088
,
1089
,
1090
,
1091
,
1092
,
1093
,
1094
,
1095
,
1096
,
1097
,
1098
,
1099
,
1100
,
1101
,
1102
,
1103
,
1104
,
1105
,
1106
,
1107
,
1108
,
1109
,
1110
,
1111
,
1112
,
1113
,
1114
,
1115
,
1116
,
1117
,
1118
,
1119
,
1120
,
1121
,
1122
,
1123
,
1124
,
1125
,
1126
,
1127
,
1128
,
1129
,
1130
,
1131
,
1132
,
1133
,
1134
,
1135
,
1136
,
1137
,
1138
,
1139
,
1140
,
1141
,
1142
,
1143
,
1144
,
1145
,
1146
,
1147
,
1148
,
1149
,
1150
,
1151
,
1152
,
1153
,
1154
,
1155
,
1156
,
1157
,
1158
,
1159
,
1160
,
1161
,
1162
,
1163
,
1164
,
1165
,
1166
,
1167
,
1168
,
1169
,
1170
,
1171
,
1172
,
1173
,
1174
,
1175
,
1176
,
1177
,
1178
,
1179
,
1180
,
1181
,
1182
,
1183
,
1184
,
1185
,
1186
,
1187
,
1188
,
1189
,
1190
,
1191
,
1192
,
1193
,
1194
,
1195
,
1196
,
1197
,
1198
,
1199
,
1200
,
1201
,
1202
,
1203
,
1204
,
1205
,
1206
,
1207
,
1208
,
1209
,
1210
,
1211
,
1212
,
1213
,
1214
,
1215
,
1216
,
1217
,
1218
,
1219
,
1220
,
1221
,
1222
,
1223
,
1224
,
1225
,
1226
,
1227
,
1228
,
1229
,
1230
,
1231
,
1232
,
1233
,
1234
,
1235
,
1236
,
1237
,
1238
,
1239
,
1240
,
1241
,
1242
,
1243
,
1244
,
1245
,
1246
,
1247
,
1248
,
1249
,
1250
,
1251
,
1252
,
1253
,
1254
,
1255
,
1256
,
1257
,
1258
,
1259
,
1260
,
1261
,
1262
,
1263
,
1264
,
1265
,
1266
,
1267
,
1268
,
1269
,
1270
,
1271
,
1272
,
1273
,
1274
,
1275
,
1276
,
1277
,
1278
,
1279
,
1280
,
1281
,
1282
,
1283
,
1284
,
1285
,
1286
,
1287
,
1288
,
1289
,
1290
,
1291
,
1292
,
1293
,
1294
,
1295
,
1296
,
1297
,
1298
,
1299
,
1300
,
1301
,
1302
,
1303
,
1304
,
1305
,
1306
,
1307
,
1308
,
1309
,
1310
,
1311
,
1312
,
1313
,
1314
,
1315
,
1316
,
1317
,
1318
,
1319
,
1320
,
1321
,
1322
,
1323
,
1324
,
1325
,
1326
,
1327
,
1328
,
1329
,
1330
,
1331
,
1332
,
1333
,
1334
,
1335
,
1336
,
1337
,
1338
,
1339
,
1340
,
1341
,
1342
,
1343
,
1344
,
1345
,
1346
,
1347
,
1348
,
1349
,
1350
,
1351
,
1352
,
1353
,
1354
,
1355
,
1356
,
1357
,
1358
,
1359
,
1360
,
1361
,
1362
,
1363
,
1364
,
1365
,
1366
,
1367
,
1368
,
1369
,
1370
,
1371
,
1372
,
1373
,
1374
,
1375
,
1376
,
1377
,
1378
,
1379
,
1380
,
1381
,
1382
,
1383
,
1384
,
1385
,
1386
,
1387
,
1388
,
1389
,
1390
,
1391
,
1392
,
1393
,
1394
,
1395
,
1396
,
1397
,
1398
,
1399
,
1400
,
1401
,
1402
,
1403
,
1404
,
1405
,
1406
,
1407
,
1408
,
1409
,
1410
,
1411
,
1412
,
1413
,
1414
,
1415
,
1416
,
1417
,
1418
,
1419
,
1420
,
1421
,
1422
,
1423
,
1424
,
1425
,
1426
,
1427
,
1428
,
1429
,
1430
,
1431
,
1432
,
1433
,
1434
,
1435
,
1436
,
1437
,
1438
,
1439
,
1440
,
1441
,
1442
,
1443
,
1444
,
1445
,
1446
,
1447
,
1448
,
1449
,
1450
,
1451
,
1452
,
1453
,
1454
,
1455
,
1456
,
1457
,
1458
,
1459
,
1460
,
1461
,
1462
,
1463
,
1464
,
1465
,
1466
,
1467
,
1468
,
1469
,
1470
,
1471
,
1472
,
1473
,
1474
,
1475
,
1476
,
1477
,
1478
,
1479
,
1480
,
1481
,
1482
,
1483
,
1484
,
1485
,
1486
,
1487
,
1488
,
1489
,
1490
,
1491
,
1492
,
1493
,
1494
,
1495
,
1496
,
1497
,
1498
,
1499
,
1500
,
1501
,
1502
]



In [ ]:
score =[
    (
46
,
1
,
0
), (
19
,
0
,
1
), (
35
,
1
,
0
), (
25
,
2
,
1
), (
0
,
3
,
0
), (
20
,
0
,
2
), (
34
,
2
,
0
), (
39
,
1
,
0
), (
6
,
3
,
0
), (
0
,
1
,
0
), (
69
,
0
,
0
), (
9
,
2
,
0
), (
18
,
0
,
2
), (
46
,
0
,
1
), (
11
,
0
,
2
), (
25
,
1
,
0
), (
34
,
0
,
3
), (
47
,
1
,
0
), (
2
,
3
,
0
), (
8
,
0
,
2
), (
2
,
0
,
0
), (
27
,
2
,
0
), (
42
,
1
,
0
), (
35
,
1
,
0
), (
34
,
1
,
0
), (
61
,
0
,
0
), (
62
,
0
,
0
), (
43
,
0
,
0
), (
1
,
2
,
0
), (
32
,
1
,
2
), (
35
,
0
,
1
), (
39
,
0
,
3
), (
37
,
1
,
0
), (
39
,
0
,
0
), (
82
,
0
,
3
), (
74
,
1
,
0
), (
33
,
2
,
3
), (
71
,
1
,
0
), (
7
,
2
,
0
), (
42
,
1
,
0
), (
78
,
0
,
0
), (
27
,
1
,
0
), (
50
,
0
,
1
), (
6
,
4
,
2
), (
59
,
0
,
1
), (
4
,
4
,
0
), (
8
,
2
,
2
), (
15
,
1
,
1
), (
33
,
1
,
0
), (
68
,
1
,
0
), (
34
,
1
,
2
), (
17
,
2
,
0
), (
83
,
1
,
0
), (
31
,
2
,
1
), (
17
,
2
,
3
), (
91
,
0
,
0
), (
67
,
0
,
0
), (
76
,
0
,
0
), (
22
,
2
,
0
), (
31
,
0
,
1
), (
27
,
0
,
1
), (
26
,
2
,
0
), (
9
,
3
,
1
), (
43
,
1
,
1
), (
6
,
1
,
2
), (
52
,
0
,
0
), (
48
,
0
,
0
), (
26
,
0
,
1
), (
50
,
0
,
0
), (
46
,
0
,
2
), (
47
,
1
,
0
), (
21
,
3
,
3
), (
10
,
2
,
0
), (
33
,
0
,
1
), (
48
,
1
,
0
), (
7
,
1
,
1
), (
42
,
0
,
1
), (
1
,
2
,
2
), (
82
,
0
,
1
), (
24
,
0
,
0
), (
28
,
1
,
0
), (
0
,
0
,
0
), (
14
,
0
,
3
), (
80
,
0
,
3
), (
38
,
0
,
0
), (
16
,
0
,
3
), (
14
,
2
,
0
), (
26
,
1
,
0
), (
17
,
2
,
2
), (
24
,
2
,
0
), (
42
,
0
,
0
), (
42
,
0
,
1
), (
47
,
1
,
0
), (
8
,
1
,
1
), (
7
,
2
,
1
), (
16
,
3
,
1
), (
46
,
0
,
0
), (
61
,
0
,
0
), (
67
,
0
,
1
), (
36
,
0
,
0
), (
15
,
1
,
0
), (
48
,
0
,
1
), (
75
,
1
,
1
), (
13
,
0
,
0
), (
32
,
0
,
1
), (
72
,
1
,
2
), (
45
,
1
,
0
), (
85
,
0
,
1
), (
5
,
0
,
0
), (
88
,
0
,
0
), (
12
,
2
,
0
), (
60
,
1
,
0
), (
42
,
0
,
3
), (
15
,
3
,
0
), (
12
,
0
,
1
), (
46
,
0
,
1
), (
1
,
1
,
2
), (
35
,
2
,
0
), (
49
,
0
,
1
), (
24
,
0
,
0
), (
33
,
0
,
0
), (
18
,
1
,
2
), (
39
,
0
,
1
), (
26
,
2
,
1
), (
35
,
0
,
0
), (
42
,
0
,
0
), (
15
,
3
,
2
), (
19
,
1
,
0
), (
14
,
2
,
0
), (
32
,
0
,
2
), (
19
,
1
,
0
), (
44
,
1
,
1
), (
48
,
0
,
0
), (
84
,
0
,
0
), (
17
,
3
,
0
), (
14
,
2
,
1
), (
14
,
0
,
1
), (
37
,
0
,
1
), (
22
,
2
,
0
), (
26
,
0
,
0
), (
26
,
1
,
0
), (
15
,
2
,
0
), (
32
,
1
,
1
), (
41
,
0
,
0
), (
10
,
4
,
1
), (
89
,
0
,
0
), (
30
,
2
,
0
), (
10
,
1
,
1
), (
19
,
1
,
0
), (
32
,
1
,
0
), (
77
,
0
,
0
), (
78
,
1
,
0
), (
63
,
0
,
0
), (
79
,
0
,
2
), (
35
,
2
,
1
), (
87
,
0
,
0
), (
28
,
2
,
0
), (
11
,
2
,
1
), (
5
,
1
,
1
), (
40
,
0
,
2
), (
80
,
0
,
1
), (
72
,
1
,
2
), (
21
,
1
,
0
), (
2
,
1
,
3
), (
22
,
0
,
0
), (
15
,
2
,
2
), (
11
,
4
,
0
), (
28
,
0
,
0
), (
85
,
1
,
1
), (
39
,
0
,
1
), (
10
,
0
,
1
), (
79
,
0
,
0
), (
42
,
0
,
1
), (
21
,
1
,
1
), (
15
,
0
,
0
), (
71
,
0
,
1
), (
20
,
0
,
0
), (
29
,
1
,
0
), (
5
,
0
,
1
), (
11
,
2
,
0
), (
7
,
3
,
1
), (
38
,
0
,
0
), (
49
,
0
,
3
), (
10
,
3
,
3
), (
80
,
1
,
0
), (
54
,
0
,
0
), (
18
,
2
,
2
), (
47
,
0
,
0
), (
32
,
1
,
3
), (
69
,
0
,
0
), (
48
,
0
,
2
), (
13
,
1
,
1
), (
89
,
1
,
0
), (
22
,
2
,
0
), (
0
,
4
,
0
), (
27
,
0
,
0
), (
19
,
3
,
0
), (
0
,
2
,
3
), (
11
,
1
,
2
), (
48
,
1
,
2
), (
15
,
3
,
0
), (
34
,
1
,
0
), (
41
,
0
,
2
), (
4
,
3
,
0
), (
17
,
0
,
0
), (
38
,
0
,
0
), (
32
,
1
,
0
), (
39
,
1
,
1
), (
29
,
1
,
0
), (
38
,
0
,
1
), (
70
,
0
,
1
), (
21
,
3
,
0
), (
5
,
3
,
0
), (
19
,
2
,
0
), (
0
,
1
,
0
), (
29
,
2
,
2
), (
21
,
1
,
0
), (
61
,
0
,
2
), (
90
,
0
,
0
), (
12
,
2
,
1
), (
45
,
0
,
2
), (
45
,
0
,
2
), (
51
,
0
,
3
), (
9
,
1
,
0
), (
50
,
0
,
1
), (
28
,
0
,
0
), (
41
,
0
,
0
), (
2
,
4
,
0
), (
79
,
1
,
1
), (
47
,
1
,
1
), (
30
,
1
,
0
), (
13
,
3
,
2
), (
31
,
0
,
1
), (
46
,
1
,
0
), (
44
,
1
,
2
), (
34
,
0
,
1
), (
28
,
1
,
0
), (
10
,
1
,
0
), (
5
,
4
,
1
), (
78
,
1
,
0
), (
31
,
0
,
0
), (
44
,
0
,
0
), (
46
,
1
,
2
), (
5
,
0
,
0
), (
25
,
2
,
0
), (
62
,
0
,
0
), (
33
,
1
,
0
), (
10
,
3
,
0
), (
65
,
0
,
2
), (
30
,
1
,
3
), (
7
,
1
,
0
), (
37
,
1
,
0
), (
41
,
0
,
0
), (
24
,
0
,
0
), (
70
,
1
,
0
), (
4
,
1
,
2
), (
20
,
2
,
2
), (
82
,
0
,
1
), (
1
,
0
,
0
), (
38
,
1
,
1
), (
64
,
1
,
0
), (
32
,
1
,
1
), (
17
,
2
,
2
), (
17
,
2
,
1
), (
86
,
0
,
2
), (
7
,
3
,
0
), (
4
,
0
,
1
), (
72
,
0
,
0
), (
1
,
1
,
2
), (
35
,
1
,
1
), (
43
,
0
,
2
), (
48
,
0
,
0
), (
20
,
1
,
1
), (
40
,
1
,
0
), (
69
,
0
,
1
), (
52
,
1
,
1
), (
78
,
0
,
2
), (
0
,
4
,
0
), (
19
,
2
,
2
), (
25
,
2
,
0
), (
44
,
1
,
3
), (
43
,
1
,
3
), (
37
,
1
,
1
), (
23
,
2
,
0
), (
60
,
1
,
0
), (
47
,
0
,
0
), (
27
,
2
,
2
), (
16
,
2
,
0
), (
8
,
4
,
0
), (
39
,
1
,
0
), (
1
,
2
,
2
), (
10
,
2
,
0
), (
25
,
0
,
2
), (
11
,
2
,
0
), (
9
,
2
,
0
), (
58
,
1
,
1
), (
31
,
1
,
0
), (
49
,
0
,
1
), (
35
,
2
,
0
), (
48
,
1
,
1
), (
5
,
1
,
2
), (
24
,
1
,
0
), (
22
,
3
,
1
), (
31
,
2
,
0
), (
50
,
1
,
2
), (
18
,
1
,
0
), (
44
,
1
,
0
), (
1
,
1
,
2
), (
43
,
1
,
1
), (
13
,
0
,
0
), (
82
,
0
,
0
), (
1
,
0
,
2
), (
79
,
1
,
1
), (
82
,
1
,
0
), (
65
,
0
,
0
), (
42
,
1
,
0
), (
34
,
0
,
1
), (
0
,
2
,
2
), (
8
,
1
,
1
), (
37
,
0
,
0
), (
40
,
1
,
0
), (
44
,
1
,
0
), (
11
,
1
,
0
), (
37
,
3
,
0
), (
10
,
3
,
1
), (
3
,
2
,
0
), (
0
,
1
,
0
), (
41
,
1
,1
), (
14
,
1
,
0
), (
5
,
1
,
0
), (
76
,
1
,
1
), (
4
,
2
,
1
), (
28
,
2
,
0
), (
11
,
0
,
1
), (
39
,
1
,
0
), (
13
,
2
,
0
), (
44
,
2
,
0
), (
74
,
0
,
2
), (
12
,
1
,
1
), (
24
,
2
,
1
), (
42
,
0
,
0
), (
37
,
0
,
2
), (
40
,
1
,
0
), (
30
,
2
,
0
), (
11
,
3
,
0
), (
5
,
2
,
0
), (
13
,
1
,
1
), (
67
,
0
,
2
), (
46
,
1
,
1
), (
26
,
2
,
1
), (
81
,
0
,
0
), (
68
,
1
,
2
), (
69
,
0
,
2
), (
89
,
0
,
1
), (
71
,
0
,
0
), (
20
,
2
,
2
), (
7
,
2
,
0
), (
76
,
0
,
2
), (
14
,
2
,
0
), (
65
,
0
,
0
), (
37
,
1
,
2
), (
15
,
2
,
0
), (
25
,
1
,
0
), (
22
,
3
,
0
), (
37
,
0
,
0
), (
76
,
0
,
3
), (
33
,
0
,
0
), (
23
,
2
,
0
), (
62
,
0
,
0
), (
7
,
0
,
0
), (
86
,
0
,
0
), (
40
,
1
,
1
), (
32
,
2
,
2
), (
21
,
0
,
1
), (
41
,
1
,
0
), (
79
,
0
,
2
), (
25
,
2
,
0
), (
76
,
0
,
1
), (
62
,
1
,
1
), (
24
,
0
,
2
), (
64
,
0
,
1
), (
34
,
0
,
0
), (
34
,
2
,
1
), (
41
,
1
,
1
), (
27
,
2
,
1
), (
36
,
1
,
0
), (
17
,
1
,
0
), (
19
,
1
,
0
), (
80
,
0
,
0
), (
78
,
0
,
0
), (
18
,
2
,
1
), (
19
,
2
,
2
), (
28
,
0
,
1
), (
39
,
0
,
0
), (
11
,
2
,
1
), (
4
,
2
,
0
), (
27
,
2
,
0
), (
67
,
1
,
0
), (
46
,
0
,
0
), (
49
,
0
,
0
), (
44
,
1
,
0
), (
19
,
1
,
0
), (
43
,
1
,
0
), (
39
,
0
,
0
), (
30
,
2
,
1
), (
34
,
1
,
0
), (
42
,
1
,
0
), (
55
,
1
,
0
), (
55
,
0
,
1
), (
72
,
1
,
1
), (
48
,
1
,
0
), (
33
,
0
,
0
), (
7
,
1
,
0
), (
21
,
1
,
2
), (
33
,
2
,
1
), (
4
,
1
,
2
), (
89
,
0
,
0
), (
2
,
1
,
0
), (
34
,
1
,
0
), (
23
,
1
,
2
), (
28
,
2
,
0
), (
85
,
0
,
1
), (
76
,
0
,
1
), (
48
,
0
,
0
), (
27
,
2
,
0
), (
44
,
1
,
2
), (
45
,
0
,
0
), (
42
,
0
,
0
), (
20
,
2
,
0
), (
64
,
1
,
0
), (
63
,
0
,
0
), (
23
,
2
,
1
), (
81
,
0
,
1
), (
54
,
0
,
0
), (
54
,
1
,
0
), (
64
,
0
,
2
), (
38
,
1
,
0
), (
59
,
0
,
1
), (
30
,
0
,
0
), (
82
,
0
,
0
), (
13
,
2
,
0
), (
80
,
0
,
0
), (
74
,
0
,
2
), (
44
,
1
,
0
), (
62
,
0
,
0
), (
6
,
3
,
0
), (
89
,
0
,
0
), (
23
,
2
,
0
), (
10
,
3
,
1
), (
4
,
0
,
0
), (
2
,
2
,
0
), (
86
,
0
,
0
), (
46
,
1
,
1
), (
39
,
0
,
2
), (
49
,
0
,
1
), (
47
,
1
,
0
), (
1
,
2
,
0
), (
20
,
2
,
0
), (
4
,
1
,
2
), (
29
,
0
,
1
), (
52
,
0
,
0
), (
45
,
0
,
0
), (
22
,
1
,
0
), (
57
,
0
,
2
), (
20
,
0
,
0
), (
7
,
1
,
3
), (
19
,
2
,
1
), (
24
,
1
,
1
), (
13
,
3
,
1
), (
16
,
1
,
0
), (
4
,
2
,
2
), (
33
,
2
,
2
), (
56
,
0
,
2
), (
77
,
1
,
1
), (
35
,
2
,
1
), (
89
,
1
,
2
), (
8
,
3
,
1
), (
30
,
1
,
1
), (
2
,
4
,
0
), (
16
,
2
,
1
), (
35
,
0
,
0
), (
15
,
1
,
2
), (
56
,
0
,
2
), (
3
,
4
,
0
), (
83
,
0
,
1
), (
28
,
2
,
3
), (
25
,
1
,
0
), (
41
,
0
,
0
), (
69
,
0
,
0
), (
49
,
0
,
0
), (
3
,
0
,
0
), (
74
,
0
,
0
), (
73
,
1
,
1
), (
11
,
2
,
0
), (
3
,
4
,
0
), (
1
,
3
,
0
), (
49
,
0
,
0
), (
79
,
0
,
0
), (
25
,
0
,
0
), (
85
,
0
,
1
), (
39
,
0
,
0
), (
5
,
1
,
1
), (
30
,
2
,
0
), (
3
,
0
,
0
), (
42
,
0
,
2
), (
19
,
2
,
1
), (
37
,
1
,
0
), (
48
,
1
,
0
), (
10
,
2
,
0
), (
23
,
2
,
3
), (
47
,
0
,
0
), (
32
,
0
,
2
), (
30
,
1
,
1
), (
23
,
2
,
1
), (
47
,
1
,
0
), (
16
,
2
,
0
), (
0
,
2
,
1
), (
65
,
0
,
3
), (
8
,
2
,
0
), (
27
,
1
,
2
), (
27
,
1
,
1
), (
25
,
2
,
0
), (
28
,
1
,
2
), (
47
,
0
,
0
), (
11
,
0
,
0
), (
15
,
2
,
1
), (
49
,
0
,
1
), (
20
,
2
,
1
), (
18
,
2
,
0
), (
45
,
0
,
2
), (
21
,
0
,
3
), (
27
,
2
,
0
), (
45
,
1
,
2
), (
26
,
2
,
1
), (
66
,
1
,
3
), (
43
,
1
,
2
), (
67
,
1
,
1
), (
28
,
0
,
0
), (
77
,
1
,
1
), (
42
,
0
,
0
), (
11
,
0
,
2
), (
25
,
1
,
1
), (
14
,
2
,
1
), (
25
,
1
,
0
), (
23
,
1
,
0
), (
3
,
0
,
0
), (
71
,
1
,
1
), (
94
,
0
,
0
), (
52
,
1
,
0
), (
33
,
1
,
0
), (
8
,
2
,
0
), (
44
,
0
,
1
), (
40
,
0
,
0
), (
5
,
3
,
0
), (
12
,
2
,
0
), (
26
,
0
,
0
), (
23
,
3
,
1
), (
8
,
1
,
0
), (
51
,
1
,
0
), (
29
,
1
,
2
), (
1
,
4
,
2
), (
77
,
1
,
1
), (
0
,
0
,
0
), (
33
,
0
,
2
), (
89
,
1
,
3
), (
22
,
0
,
2
), (
55
,
0
,
2
), (
30
,
0
,
1
), (
28
,
0
,
3
), (
68
,
1
,
2
), (
48
,
0
,
0
), (
30
,
1
,
2
), (
21
,
1
,
1
), (
32
,
2
,
1
), (
7
,
2
,
0
), (
45
,
0
,
2
), (
10
,
4
,
0
), (
46
,
1
,
0
), (
44
,
1
,
0
), (
2
,
3
,
1
), (
27
,
1
,
0
), (
55
,
1
,
1
), (
39
,
0
,
0
), (
19
,
0
,
2
), (
27
,
1
,
1
), (
78
,
0
,
0
), (
80
,
0
,
0
), (
22
,
2
,
2
), (
27
,
2
,
0
), (
53
,
0
,
3
), (
42
,
0
,
2
), (
41
,
1
,
0
), (
4
,
3
,
0
), (
29
,
0
,
1
), (
59
,
0
,
1
), (
3
,
0
,
2
), (
7
,
2
,
1
), (
13
,
1
,
1
), (
10
,
4
,
0
), (
17
,
3
,
0
), (
1
,
4
,
0
), (
26
,
1
,
2
), (
87
,
0
,
0
), (
23
,
0
,
1
), (
45
,
0
,
0
), (
26
,
2
,
0
), (
26
,
1
,
0
), (
54
,
0
,
0
), (
43
,
0
,
0
), (
25
,
0
,
0
), (
16
,
1
,
1
), (
21
,
2
,
2
), (
40
,
0
,
1
), (
81
,
0
,
0
), (
16
,
1
,
1
), (
19
,
2
,
1
), (
83
,
0
,
0
), (
4
,
0
,
0
), (
19
,
1
,
0
), (
21
,
1
,
0
), (
7
,
1
,
0
), (
44
,
0
,
1
), (
8
,
2
,
0
), (
40
,
0
,
0
), (
47
,
0
,
0
), (
17
,
2
,
0
), (
20
,
0
,
2
), (
32
,
2
,
1
), (
10
,
1
,
2
), (
19
,
1
,
0
), (
14
,
0
,
3
), (
23
,
0
,
0
), (
66
,
1
,
1
), (
73
,
1
,
2
), (
48
,
1
,
0
), (
62
,
1
,
1
), (
9
,
1
,
0
), (
22
,
0
,
0
), (
87
,
0
,
0
), (
15
,
2
,
0
), (
21
,
2
,
0
), (
48
,
1
,
0
), (
11
,
0
,
0
), (
17
,
2
,
0
), (
3
,
4
,
1
), (
19
,
0
,
0
), (
62
,
1
,
2
), (
35
,
0
,
0
),(
8
,
3
,
0
),(
16
,
2
,
0
),(
5
,
0
,
0
),(
35
,
0
,
0
),(
2
,
3
,
0
),(
9
,
3
,2
), (
34
,
0
,
0
), (
10
,
1
,
0
), (
17
,
2
,
0
), (
14
,
1
,
0
), (
11
,
2
,
1
), (
6
,
2
,
2
), (
23
,
0
,
0
), (
22
,
3
,
2
), (
12
,
2
,
0
), (
19
,
0
,
1
), (
68
,
0
,
0
), (
22
,
2
,
1
), (
40
,
1
,
0
), (
29
,
2
,
2
), (
17
,
2
,
0
), (
40
,
1
,
1
), (
26
,
1
,
0
), (
38
,
1
,
1
), (
2
,
2
,
2
), (
9
,
2
,
2
), (
34
,
0
,
1
), (
56
,
0
,
0
), (
20
,
3
,
0
), (
2
,
0
,
0
), (
46
,
0
,
2
), (
38
,
0
,
0
), (
38
,
1
,
0
), (
29
,
0
,
0
), (
25
,
0
,
1
), (
79
,
1
,
1
), (
0
,
4
,
1
), (
72
,
1
,
0
), (
1
,
0
,
0
), (
37
,
0
,
0
), (
25
,
1
,
0
), (
47
,
1
,
1
), (
5
,
1
,
1
), (
29
,
2
,
2
), (
14
,
2
,
2
), (
26
,
2
,
0
), (
47
,
1
,
1
), (
21
,
1
,
1
), (
87
,
0
,
0
), (
31
,
1
,
0
), (
19
,
1
,
0
), (
25
,
1
,
1
), (
34
,
1
,
0
), (
12
,
1
,
1
), (
42
,
1
,
0
), (
7
,
0
,
2
), (
8
,
2
,
0
), (
89
,
0
,
3
), (
79
,
0
,
0
), (
14
,
2
,
0
), (
38
,
0
,
0
), (
42
,
1
,
0
), (
26
,
2
,
1
), (
45
,
0
,
0
), (
16
,
1
,
1
), (
60
,
0
,
0
), (
8
,
1
,
0
), (
4
,
1
,
0
), (
29
,
1
,
2
), (
1
,
2
,
0
), (
71
,
1
,
0
), (
60
,
0
,
1
), (
82
,
0
,
0
), (
39
,
1
,
1
), (
20
,
2
,
1
), (
29
,
1
,
2
), (
82
,
1
,
0
), (
34
,
1
,
3
), (
44
,
1
,
1
), (
24
,
0
,
0
), (
5
,
0
,
0
), (
0
,
2
,
1
), (
24
,
1
,
1
), (
7
,
0
,
2
), (
28
,
2
,
0
), (
46
,
0
,
0
), (
9
,
0
,
1
), (
45
,
1
,
1
), (
16
,
0
,
0
), (
12
,
3
,
1
), (
80
,
0
,
1
), (
19
,
2
,
1
), (
21
,
2
,
1
), (
43
,
0
,
1
), (
43
,
0
,
2
), (
83
,
0
,
1
), (
3
,
2
,
0
), (
39
,
1
,
1
), (
34
,
1
,
2
), (
7
,
4
,
1
), (
29
,
0
,
3
), (
74
,
0
,
1
), (
65
,
0
,
1
), (
37
,
1
,
3
), (
49
,
0
,
0
), (
38
,
1
,
2
), (
25
,
1
,
0
), (
25
,
1
,
0
), (
35
,
2
,
0
), (
34
,
2
,
0
), (
52
,
0
,
2
), (
19
,
3
,
0
), (
45
,
1
,
1
), (
21
,
1
,
0
), (
23
,
2
,
0
), (
17
,
1
,
0
), (
13
,
1
,
1
), (
24
,
1
,
0
), (
69
,
1
,
0
), (
0
,
2
,
0
), (
15
,
0
,
1
), (
49
,
0
,
1
), (
40
,
1
,
0
), (
1
,
0
,
0
), (
4
,
4
,
0
), (
16
,
1
,
0
), (
2
,
4
,
2
), (
6
,
4
,
1
), (
61
,
0
,
2
), (
27
,
2
,
0
), (
23
,
2
,
2
), (
44
,
0
,
2
), (
32
,
1
,
2
), (
1
,
4
,
0
), (
65
,
0
,
0
), (
20
,
2
,
0
), (
23
,
0
,
0
), (
28
,
2
,
0
), (
47
,
1
,
1
), (
36
,
0
,
0
), (
2
,
0
,
0
), (
48
,
1
,
3
), (
14
,
1
,
1
), (
21
,
2
,
0
), (
35
,
0
,
0
), (
28
,
0
,
0
), (
35
,
2
,
2
), (
11
,
3
,
1
), (
17
,
0
,
1
), (
25
,
1
,
0
), (
13
,
0
,
3
), (
0
,
3
,
2
), (
19
,
2
,
0
), (
43
,
1
,
0
), (
42
,
0
,
1
), (
58
,
0
,
1
), (
40
,
1
,
2
), (
37
,
1
,
1
), (
57
,
0
,
2
), (
27
,
1
,
0
), (
33
,
1
,
1
), (
22
,
0
,
0
), (
37
,
0
,
0
), (
39
,
0
,
2
), (
21
,
1
,
0
), (
49
,
0
,
0
), (
78
,
0
,
0
), (
77
,
0
,
0
), (
29
,
0
,
0
), (
2
,
2
,
0
), (
40
,
0
,
2
), (
1
,
1
,
1
), (
15
,
3
,
0
), (
69
,
1
,
1
), (
24
,
0
,
3
), (
29
,
1
,
1
), (
77
,
0
,
0
), (
30
,
2
,
1
), (
31
,
0
,
0
), (
45
,
0
,
0
), (
1
,
0
,
0
), (
40
,
0
,
0
), (
1
,
0
,
1
), (
35
,
0
,
0
), (
56
,
1
,
2
), (
88
,
0
,
0
), (
29
,
2
,
0
), (
34
,
2
,
1
), (
24
,
0
,
1
), (
47
,
1
,
2
), (
71
,
0
,
1
), (
11
,
0
,
1
), (
22
,
2
,
0
), (
9
,
0
,
0
), (
2
,
0
,
1
), (
15
,
3
,
1
), (
58
,
0
,
0
), (
16
,
0
,
0
), (
46
,
1
,
0
), (
11
,
0
,
2
), (
88
,
0
,
2
), (
20
,
0
,
1
), (
47
,
1
,
0
), (
19
,
2
,
1
), (
24
,
1
,
0
), (
31
,
0
,
2
), (
0
,
4
,
0
), (
46
,
0
,
2
), (
2
,
3
,
1
), (
33
,
2
,
0
), (
11
,
4
,
0
), (
42
,
1
,
1
), (
35
,
2
,
0
), (
23
,
1
,
1
), (
47
,
0
,
1
), (
75
,
0
,
3
), (
30
,
2
,
0
), (
12
,
0
,
2
), (
11
,
1
,
1
), (
32
,
2
,
0
), (
7
,
3
,
1
), (
41
,
1
,
1
), (
3
,
1
,
0
), (
36
,
0
,
0
), (
17
,
3
,
0
), (
16
,
1
,
0
), (
26
,
1
,
0
), (
8
,
2
,
0
), (
7
,
2
,
0
), (
19
,
0
,
1
), (
9
,
2
,
2
), (
22
,
2
,
0
), (
5
,
0
,
0
), (
15
,
2
,
2
), (
45
,
0
,
2
), (
39
,
0
,
0
), (
2
,
3
,
0
), (
43
,
0
,
0
), (
44
,
0
,
3
), (
20
,
2
,
0
), (
32
,
2
,
1
), (
43
,
0
,
0
), (
80
,
1
,
0
), (
47
,
0
,
1
), (
62
,
0
,
1
), (
0
,
1
,
0
), (
20
,
0
,
1
), (
28
,
2
,
0
), (
27
,
1
,
0
), (
24
,
2
,
0
), (
77
,
1
,
1
), (
23
,
1
,
3
), (
49
,
1
,
1
), (
47
,
0
,
2
), (
82
,
0
,
0
), (
72
,
0
,
2
), (
9
,
0
,
0
), (
52
,
1
,
0
), (
50
,
3
,
1
), (
15
,
2
,
0
), (
20
,
3
,
1
), (
11
,
1
,
0
), (
48
,
0
,
0
), (
0
,
2
,
1
), (
14
,
2
,
1
), (
20
,
0
,
2
), (
20
,
2
,
2
), (
70
,
0
,
0
), (
77
,
0
,
0
), (
89
,
0
,
0
), (
16
,
2
,
1
), (
30
,
1
,
1
), (
6
,
1
,
1
), (
26
,
2
,
1
), (
46
,
0
,
0
), (
48
,
1
,
1
), (
20
,
2
,
2
), (
13
,
1
,
1
), (
13
,
1
,
2
), (
6
,
4
,
2
), (
38
,
1
,
1
), (
5
,
2
,
0
), (
3
,
3
,
0
), (
32
,
2
,
0
), (
22
,
3
,
0
), (
71
,
0
,
0
), (
33
,
0
,
2
), (
48
,
0
,
0
), (
35
,
0
,
0
), (
32
,
1
,
0
), (
4
,
3
,
0
), (
37
,
0
,
0
), (
30
,
1
,
0
), (
78
,
0
,
0
), (
49
,
0
,
1
), (
0
,
0
,
1
), (
24
,
2
,
1
), (
48
,
1
,
1
), (
35
,
0
,
1
), (
6
,
2
,
0
), (
17
,
0
,
0
), (
42
,
0
,
0
), (
45
,
0
,
1
), (
70
,
0
,
0
), (
30
,
0
,
0
), (
42
,
1
,
0
), (
43
,
0
,
0
), (
46
,
0
,
1
), (
24
,
1
,
1
), (
3
,
1
,
0
), (
29
,
1
,
1
), (
14
,
2
,
0
), (
41
,
0
,
2
), (
80
,
0
,
1
), (
31
,
2
,
0
), (
20
,
2
,
0
), (
29
,
0
,
0
), (
4
,
1
,
2
), (
39
,
1
,
0
), (
17
,
1
,
0
), (
28
,
2
,
1
), (
83
,
0
,
1
), (
12
,
2
,
1
), (
27
,
2
,
0
), (
70
,
0
,
1
), (
28
,
0
,
1
),(
5,
2,
0
),(
45,
1,
3
),(
12,
1,
2
),(
40,
0,
1
),(
54,
2,
1
),(
0,3
,
0
), (
7
,
1
,
1
), (
49
,
0
,
0
), (
8
,
3
,
1
), (
23
,
3
,
1
), (
1
,
2
,
0
), (
54
,
0
,
2
), (
39
,
0
,
0
), (
4
,
3
,
1
), (
38
,
1
,
1
), (
23
,
1
,
0
), (
45
,
1
,
1
), (
23
,
0
,
0
), (
48
,
1
,
0
), (
49
,
1
,
0
), (
27
,
2
,
0
), (
45
,
0
,
0
), (
17
,
0
,
1
), (
10
,
0
,
0
), (
27
,
1
,
1
), (
37
,
0
,
0
), (
27
,
0
,
1
), (
84
,
1
,
3
), (
37
,
0
,
0
), (
43
,
0
,
0
), (
72
,
0
,
0
), (
3
,
4
,
0
), (
41
,
0
,
0
), (
24
,
1
,
0
), (
9
,
1
,
1
), (
48
,
1
,
2
), (
37
,
1
,
1
), (
27
,
2
,
0
), (
65
,
1
,
0
), (
18
,
0
,
1
), (
14
,
1
,
0
), (
28
,
0
,
0
), (
2
,
3
,
1
), (
43
,
0
,
1
), (
37
,
1
,
0
), (
34
,
0
,
1
), (
24
,
0
,
1
), (
15
,
0
,
2
), (
20
,
1
,
1
), (
41
,
0
,
1
), (
5
,
0
,
1
), (
31
,
0
,
2
), (
43
,
0
,
1
), (
1
,
1
,
2
), (
7
,
2
,
2
), (
62
,
0
,
0
), (
2
,
0
,
0
), (
24
,
2
,
0
), (
30
,
0
,
2
), (
22
,
2
,
0
), (
50
,
0
,
2
), (
11
,
2
,
3
), (
31
,
2
,
0
), (
8
,
0
,
2
), (
41
,
0
,
0
), (
42
,
1
,
0
), (
24
,
1
,
1
), (
19
,
0
,
2
), (
43
,
0
,
0
), (
81
,
0
,
1
), (
48
,
1
,
1
), (
10
,
2
,
0
), (
21
,
2
,
1
), (
35
,
2
,
1
), (
28
,
1
,
0
), (
37
,
1
,
0
), (
26
,
1
,
0
), (
9
,
0
,
2
), (
55
,
0
,
0
), (
31
,
0
,
0
), (
14
,
2
,
0
), (
32
,
0
,
0
), (
85
,
0
,
2
), (
46
,
1
,
0
), (
28
,
0
,
0
), (
52
,
1
,
0
), (
76
,
0
,
1
), (
9
,
2
,
0
), (
3
,
4
,
3
), (
39
,
1
,
1
), (
2
,
4
,
0
), (
33
,
2
,
0
), (
78
,
1
,
2
), (
58
,
0
,
1
), (
23
,
3
,
0
), (
34
,
1
,
1
), (
15
,
0
,
0
), (
48
,
1
,
0
), (
76
,
1
,
0
), (
28
,
2
,
0
), (
0
,
2
,
3
), (
33
,
0
,
0
), (
15
,
2
,
0
), (
3
,
2
,
0
), (
14
,
1
,
1
), (
29
,
0
,
0
), (
87
,
0
,
0
), (
9
,
2
,
1
), (
9
,
1
,
0
), (
44
,
1
,
1
), (
37
,
1
,
0
), (
17
,
2
,
1
), (
7
,
0
,
0
), (
9
,
0
,
0
), (
39
,
0
,
2
), (
39
,
0
,
0
), (
5
,
3
,
0
), (
45
,
0
,
0
), (
30
,
0
,
0
), (
19
,
2
,
0
), (
47
,
0
,
1
), (
32
,
0
,
2
), (
12
,
3
,
1
), (
33
,
1
,
1
), (
64
,
0
,
2
), (
45
,
1
,
2
), (
31
,
2
,
0
), (
18
,
2
,
0
), (
28
,
1
,
0
), (
39
,
0
,
0
), (
18
,
2
,
0
), (
9
,
0
,
0
), (
46
,
0
,
0
), (
11
,
0
,
2
), (
49
,
0
,
2
), (
16
,
0
,
0
), (
27
,
0
,
2
), (
47
,
1
,
1
), (
65
,
0
,
3
), (
36
,
1
,
0
), (
24
,
2
,
0
), (
41
,
0
,
1
), (
44
,
1
,
0
), (
33
,
2
,
0
), (
27
,
1
,
0
), (
14
,
0
,
2
), (
41
,
0
,
1
), (
62
,
0
,
0
), (
36
,
0
,
2
), (
21
,
2
,
0
), (
79
,
0
,
1
), (
11
,
2
,
0
), (
42
,
0
,
0
), (
4
,
1
,
0
), (
28
,
2
,
0
), (
20
,
0
,
1
), (
44
,
1
,
2
), (
36
,
1
,
2
), (
84
,
0
,
2
), (
41
,
0
,
1
), (
38
,
1
,
0
), (
34
,
0
,
0
), (
23
,
2
,
0
), (
23
,
2
,
0
), (
44
,
1
,
1
), (
2
,
1
,
1
), (
23
,
1
,
1
), (
55
,
0
,
2
), (
44
,
1
,
1
), (
43
,
0
,
1
), (
30
,
2
,
0
), (
43
,
0
,
0
), (
39
,
0
,
0
), (
82
,
0
,
0
), (
31
,
1
,
0
), (
14
,
0
,
0
), (
40
,
0
,
2
), (
35
,
1
,
0
), (
23
,
0
,
2
), (
2
,
2
,
0
), (
12
,
1
,
2
), (
77
,
0
,
2
), (
59
,
0
,
0
), (
28
,
1
,
0
), (
54
,
0
,
0
), (
41
,
0
,
0
), (
45
,
1
,
0
), (
28
,
0
,
1
), (
32
,
1
,
3
), (
27
,
2
,
2
), (
84
,
1
,
0
), (
49
,
0
,
3
), (
4
,
3
,
2
), (
44
,
0
,
2
), (
43
,
0
,
0
), (
12
,
3
,
1
), (
47
,
0
,
1
), (
40
,
0
,
0
), (
24
,
1
,
1
), (
0
,
1
,
2
), (
39
,
4
,
0
), (
17
,
0
,
0
), (
60
,
0
,
0
), (
32
,
0
,
1
), (
3
,
0
,
2
), (
6
,
2
,
1
), (
30
,
0
,
1
), (
26
,
0
,
1
), (
17
,
3
,
1
), (
58
,
0
,
0
), (
32
,
0
,
0
), (
13
,
2
,
1
), (
85
,
1
,
0
), (
34
,
2
,
0
), (
10
,
1
,
1
), (
82
,
0
,
0
), (
15
,
0
,
0
), (
78
,
0
,
1
), (
45
,
0
,
0
), (
25
,
2
,
3
), (
14
,
0
,
0
), (
40
,
1
,
1
), (
19
,
1
,
0
), (
5
,
1
,
1
), (
15
,
2
,
0
), (
9
,
3
,
0
), (
23
,
2
,
0
), (
22
,
2
,
0
), (
48
,
1
,
0
), (
0
,
4
,
0
), (
37
,
1
,
1
), (
45
,
1
,
0
), (
15
,
0
,
0
), (
42
,
0
,
1
), (
55
,
0
,
1
), (
43
,
1
,
1
), (
3
,
2
,
1
), (
32
,
2
,
0
), (
21
,
2
,
0
), (
82
,
0
,
0
), (
22
,
1
,
0
), (
79
,
1
,
0
), (
2
,
4
,
0
), (
88
,
1
,
1
), (
32
,
1
,
0
), (
32
,
0
,
2
), (
14
,
2
,
0
), (
6
,
3
,
2
), (
2
,
2
,
1
), (
49
,
0
,
1
), (
49
,
0
,
2
), (
17
,
0
,
2
), (
33
,
1
,
3
), (
23
,
1
,
1
), (
33
,
0
,
2
), (
15
,
2
,
0
), (
33
,
2
,
0
), (
34
,
2
,
0
), (
48
,
1
,
0
), (
46
,
0
,
0
), (
18
,
2
,
0
), (
28
,
1
,
0
), (
2
,
2
,
0
), (
32
,
1
,
0
), (
9
,
0
,
0
), (
70
,
0
,
0
), (
17
,
2
,
0
), (
32
,
2
,
2
), (
79
,
1
,
0
), (
78
,
0
,
0
), (
36
,
0
,
0
), (
40
,
0
,
1
), (
64
,
1
,
3
), (
25
,
0
,
0
), (
23
,
3
,
1
), (
65
,
0
,
3
), (
3
,
2
,
0
), (
21
,
2
,
1
), (
12
,
1
,
2
), (
12
,
2
,
0
), (
3
,
1
,
0
), (
34
,
1
,
0
), (
70
,
1
,
2
), (
30
,
0
,
0
), (
4
,
2
,
0
), (
23
,
1
,
3
), (
6
,
4
,
0
), (
4
,
4
,
0
), (
22
,
3
,
0
), (
9
,
0
,
0
), (
89
,
0
,
0
), (
25
,
2
,
1
), (
39
,
1
,
1
), (
46
,
1
,
1
), (
74
,
1
,
0
), (
12
,
2
,
0
), (
3
,
0
,
0
), (
24
,
0
,
0
), (
44
,
0
,
0
), (
7
,
3
,
3
), (
11
,
1
,
0
), (
27
,
0
,
0
), (
6
,
4
,
2
), (
71
,
1
,
1
), (
8
,
0
,
1
), (
33
,
0
,
0
), (
1
,
2
,
1
), (
49
,
0
,
2
), (
35
,
2
,
0
), (
39
,
0
,
1
), (
5
,
2
,
0
), (
25
,
0
,
0
), (
54
,
0
,
1
), (
35
,
1
,
1
), (
5
,
1
,
2
), (
46
,
0
,
0
), (
12
,
2
,
0
), (
25
,
0
,
0
), (
84
,
0
,
0
), (
9
,
2
,
3
), (
19
,
1
,
1
), (
24
,
2
,
2
), (
38
,
0
,
1
), (
15
,
1
,
2
), (
66
,
0
,
1
), (
14
,
3
,1
), (
64
,
0
,
0
), (
8
,
4
,
0
), (
87
,
0
,
0
), (
2
,
1
,
1
), (
47
,
1
,
0
), (
33
,
2
,
2
), (
35
,
0
,
1
), (
45
,
1
,
3
), (
31
,
1
,
0
), (
46
,
0
,
0
), (
2
,
3
,
0
), (
36
,
1
,
1
), (
14
,
3
,
3
), (
79
,
0
,
0
), (
4
,
4
,
1
), (
29
,
0
,
2
), (
14
,
2
,
0
), (
49
,
0
,
0
), (
20
,
1
,
0
), (
14
,
0
,
0
), (
12
,
2
,
3
), (
47
,
0
,
0
), (
20
,
3
,
2
), (
36
,
0
,
3
), (
36
,
0
,
0
), (
41
,
1
,
0
), (
8
,
4
,
0
), (
39
,
1
,
1
), (
32
,
0
,
1
), (
3
,
2
,
2
), (
35
,
1
,
0
), (
13
,
2
,
0
), (
10
,
0
,
0
), (
35
,
1
,
0
), (
77
,
0
,
0
), (
48
,
0
,
1
), (
40
,
0
,
1
), (
32
,
1
,
0
), (
12
,
2
,
0
), (
43
,
0
,
0
), (
30
,
1
,
0
), (
20
,
0
,
1
), (
22
,
1
,
1
), (
1
,
2
,
1
), (
5
,
1
,
0
), (
36
,
2
,
0
), (
76
,
0
,
1
), (
8
,
1
,
0
), (
30
,
2
,
0
), (
9
,
0
,
1
), (
34
,
2
,
0
), (
13
,
2
,
1
), (
39
,
0
,
0
), (
26
,
0
,
0
), (
32
,
0
,
0
), (
27
,
1
,
1
), (
68
,
0
,
1
), (
6
,
4
,
0
), (
36
,
0
,
1
), (
16
,
2
,
0
), (
58
,
0
,
0
), (
40
,
0
,
1
), (
23
,
0
,
1
), (
16
,
3
,
0
), (
43
,
0
,
0
), (
39
,
1
,
1
), (
26
,
0
,
0
), (
48
,
0
,
2
), (
53
,
0
,
0
), (
37
,
1
,
1
), (
47
,
0
,
1
), (
34
,
2
,
2
), (
17
,
0
,
0
), (
25
,
1
,
3
), (
60
,
0
,
0
), (
42
,
1
,
0
), (
13
,
2
,
0
), (
32
,
2
,
3
), (
14
,
3
,
0
), (
31
,
1
,
1
), (
10
,
2
,
2
), (
75
,
0
,
0
), (
40
,
0
,
1
), (
33
,
0
,
1
), (
85
,
1
,
0
), (
30
,
0
,
2
), (
44
,
1
,
0
), (
34
,
1
,
1
), (
43
,
1
,
0
), (
14
,
2
,
0
), (
49
,
1
,
1
), (
53
,
0
,
0
), (
88
,
1
,
0
), (
30
,
2
,
1
), (
17
,
0
,
1
), (
5
,
2
,
1
), (
12
,
2
,
1
), (
24
,
0
,
1
), (
9
,
1
,
0
), (
44
,
1
,
0
), (
34
,
0
,
0
), (
33
,
2
,
3
), (
41
,
0
,
0
), (
8
,
4
,
0
), (
48
,
1
,
0
), (
82
,
0
,
0
), (
33
,
0
,
0
), (
8
,
3
,
0
), (
15
,
1
,
1
), (
23
,
3
,
0
), (
29
,
0
,
2
), (
35
,
0
,
1
), (
43
,
1
,
1
), (
29
,
1
,
2
), (
4
,
2
,
2
), (
1
,
0
,
1
), (
20
,
3
,
0
), (
53
,
1
,
0
), (
30
,
2
,
0
), (
81
,
0
,
2
), (
18
,
1
,
2
), (
27
,
2
,
2
), (
42
,
1
,
0
), (
60
,
0
,
0
), (
82
,
0
,
0
), (
37
,
0
,
0
), (
52
,
0
,
0
), (
30
,
2
,
1
), (
69
,
1
,
0
), (
30
,
2
,
1
), (
2
,
4
,
0
), (
60
,
0
,
0
), (
36
,
1
,
0
), (
55
,
1
,
1
), (
80
,
1
,
0
), (
14
,
2
,
2
), (
33
,
2
,
0
), (
35
,
1
,
0
), (
21
,
2
,
0
), (
8
,
2
,
0
), (
43
,
1
,
0
), (
19
,
2
,
1
), (
25
,
1
,
0
), (
30
,
2
,
1
), (
17
,
2
,
2
), (
24
,
0
,
0
), (
3
,
2
,
0
), (
20
,
3
,
1
), (
18
,
0
,
0
), (
10
,
4
,
0
), (
33
,
0
,
0
), (
26
,
1
,
0
), (
1
,
1
,
0
), (
40
,
1
,
2
), (
13
,
1
,
1
), (
0
,
4
,
0
), (
24
,
0
,
0
), (
34
,
0
,
0
), (
33
,
1
,
0
), (
33
,
0
,
2
), (
0
,
2
,
0
), (
54
,
1
,
0
), (
13
,
2
,
0
), (
24
,
0
,
1
), (
46
,
0
,
0
), (
45
,
0
,
0
), (
38
,
1
,
0
), (
26
,
1
,
0
), (
44
,
0
,
2
), (
9
,
0
,
0
), (
20
,
0
,
1
), (
64
,
0
,
0
), (
3
,
2
,
0
), (
17
,
1
,
2
), (
39
,
1
,
0
), (
13
,
1
,
3
), (
14
,
1
,
1
), (
46
,
1
,
0
), (
1
,
1
,
2
), (
33
,
0
,
0
), (
39
,
0
,
0
), (
41
,
1
,
0
), (
24
,
2
,
0
), (
38
,
1
,
2
), (
58
,
1
,
0
), (
9
,
2
,
3
), (
48
,
1
,
0
), (
63
,
0
,
0
), (
26
,
2
,
0
), (
48
,
0
,
1
), (
21
,
1
,
2
), (
10
,
3
,
3
), (
6
,
0
,
0
), (
33
,
2
,
0
), (
3
,
0
,
3
), (
0
,
4
,
0
), (
84
,
0
,
1
), (
19
,
0
,
0
), (
41
,
1
,
1
), (
21
,
1
,
1
), (
45
,
0
,
3
), (
12
,
3
,
0
)]

In [ ]:
player_arr = np.array(player)
score_arr = np.array(score)

In [ ]:
all_rounders = np.sum((score_arr[:,0] > 35) & (score_arr[:,1] >= 2))
print(all_rounders)

6


In [ ]:
score_arr.ndim

2

In [ ]:
zero_run_count = np.sum(score_arr[:,0] == 0)
print(zero_run_count)

26


In [ ]:
max_wickets = np.max(score_arr[:,1])
print(max_wickets)

4


In [ ]:
max_run_index = np.argmax(score_arr[:,0])
max_run_player = player_arr[max_run_index]

In [ ]:
print(max_run_player)

548


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
arr[1, 2]

np.int64(6)

In [ ]:
arr.reshape(1, 3, 3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
arr.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
arr[..., 1]

array([2, 5, 8])

In [ ]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])


In [ ]:
arr1 & arr2

array([0, 0, 2])

In [ ]:
np.add(arr1, arr2)

array([5, 7, 9])

In [ ]:
arr1 = np.array([[1, 2, 3]])

arr2 = np.array([10, 20])

In [ ]:
reshaped_arr1 = arr1.reshape(3, 1)
reshaped_arr1

array([[1],
       [2],
       [3]])

In [ ]:
reshaped_arr1 = arr1.reshape(1, 3)
reshaped_arr1

array([[1, 2, 3]])

In [ ]:
import pandas as pd


In [ ]:
df_empty = pd.DataFrame()

In [ ]:
data = {
    'Name':['Alice', 'Bob', 'Chandini', 'Dawood'],
    'Age': [25,30,18,22],
    'City': ['Mumbai', 'Kolkata', 'Delhi', 'Bengaluru']
}
df1= pd.DataFrame(data = data)

In [ ]:
df1

,Name,Age,City
0,Alice,25,Mumbai
1,Bob,30,Kolkata
2,Chandini,18,Delhi
3,Dawood,22,Bengaluru


In [ ]:
df1.dtypes

,0
Name,object
Age,int64
City,object


In [ ]:
df1.ndim

2

In [ ]:
df1.shape

(4, 3)

In [ ]:
df1.shape

(4, 3)

In [ ]:
df1.size

12

In [ ]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
df1.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [ ]:
df1.values

array([['Alice', 25, 'Mumbai'],
       ['Bob', 30, 'Kolkata'],
       ['Chandini', 18, 'Delhi'],
       ['Dawood', 22, 'Bengaluru']], dtype=object)

In [ ]:
names = pd.Series(['Alice', 'Bob', 'Chandni', 'Dawood'])
ages = pd.Series([25, 30, 18, 22])
cities = pd.Series(['Mumbai', 'Kolkata', 'Delhi', 'Bengaluru'])

df2 = pd.DataFrame({'Name':names,'Age':ages, 'City':cities})

In [ ]:
df2

,Name,Age,City
0,Alice,25,Mumbai
1,Bob,30,Kolkata
2,Chandni,18,Delhi
3,Dawood,22,Bengaluru


In [ ]:
import pandas as pd


In [ ]:
df_ipl = pd.read_csv('matches_data.csv')

In [ ]:
df_ipl = pd.read_csv('matches_data.csv', index_col = 'id')

In [ ]:
df_ipl.index

Index([ 335982,  335983,  335984,  335985,  335986,  335987,  335988,  335989,
        335990,  335991,
       ...
       1359539, 1359540, 1359541, 1359542, 1359543, 1359544, 1370350, 1370351,
       1370352, 1370353],
      dtype='int64', name='id', length=1019)

In [ ]:
df_ipl.head()

,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
id,,,,,,,,,,,,,,,,,,,
335982,2007/08,Bengaluru,18-04-2008,League,BB McCullum,M Chinnaswamy Stadium,Bengaluru,Kolkata,Bengaluru,field,Kolkata,runs,140,223,20.0,N,standard,Asad Rauf,RE Koertzen
335983,2007/08,Chandigarh,19-04-2008,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Punjab,Chennai,Chennai,bat,Chennai,runs,33,241,20.0,N,standard,MR Benson,SL Shastri
335984,2007/08,Delhi,19-04-2008,League,MF Maharoof,Feroz Shah Kotla,Delhi,Rajasthan,Rajasthan,bat,Delhi,wickets,9,130,20.0,N,standard,Aleem Dar,GA Pratapkumar
335985,2007/08,Mumbai,20-04-2008,League,MV Boucher,Wankhede Stadium,Mumbai,Bengaluru,Mumbai,bat,Bengaluru,wickets,5,166,20.0,N,standard,SJ Davis,DJ Harper
335986,2007/08,Kolkata,20-04-2008,League,DJ Hussey,Eden Gardens,Kolkata,Hyderabad,Hyderabad,bat,Kolkata,wickets,5,111,20.0,N,standard,BF Bowden,K Hariharan


In [ ]:
df_ipl.dtypes

,0
season,object
city,object
date,object
match_type,object
player_of_match,object
venue,object
team1,object
team2,object
toss_winner,object
toss_decision,object


In [ ]:
df_ipl.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1019 entries, 335982 to 1370353
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   season           1019 non-null   object 
 1   city             1019 non-null   object 
 2   date             1019 non-null   object 
 3   match_type       1019 non-null   object 
 4   player_of_match  1019 non-null   object 
 5   venue            1019 non-null   object 
 6   team1            1019 non-null   object 
 7   team2            1019 non-null   object 
 8   toss_winner      1019 non-null   object 
 9   toss_decision    1019 non-null   object 
 10  winner           1019 non-null   object 
 11  result           1019 non-null   object 
 12  result_margin    1019 non-null   int64  
 13  target_runs      1019 non-null   int64  
 14  target_overs     1019 non-null   float64
 15  super_over       1019 non-null   object 
 16  method           1019 non-null   object 
 17  umpire1    

In [ ]:
df_ipl.describe()

,result_margin,target_runs,target_overs
count,1019.000000,1019.000000,1019.000000
mean,16.979392,164.027478,19.760746
std,21.733621,32.225495,1.564372
min,0.000000,43.000000,5.000000
25%,5.000000,145.000000,20.000000
50%,8.000000,165.000000,20.000000
75%,19.000000,185.000000,20.000000
max,146.000000,264.000000,20.000000


In [ ]:
df_ipl.head(n = 10)

,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
id,,,,,,,,,,,,,,,,,,,
335982,2007/08,Bengaluru,18-04-2008,League,BB McCullum,M Chinnaswamy Stadium,Bengaluru,Kolkata,Bengaluru,field,Kolkata,runs,140,223,20.0,N,standard,Asad Rauf,RE Koertzen
335983,2007/08,Chandigarh,19-04-2008,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Punjab,Chennai,Chennai,bat,Chennai,runs,33,241,20.0,N,standard,MR Benson,SL Shastri
335984,2007/08,Delhi,19-04-2008,League,MF Maharoof,Feroz Shah Kotla,Delhi,Rajasthan,Rajasthan,bat,Delhi,wickets,9,130,20.0,N,standard,Aleem Dar,GA Pratapkumar
335985,2007/08,Mumbai,20-04-2008,League,MV Boucher,Wankhede Stadium,Mumbai,Bengaluru,Mumbai,bat,Bengaluru,wickets,5,166,20.0,N,standard,SJ Davis,DJ Harper
335986,2007/08,Kolkata,20-04-2008,League,DJ Hussey,Eden Gardens,Kolkata,Hyderabad,Hyderabad,bat,Kolkata,wickets,5,111,20.0,N,standard,BF Bowden,K Hariharan
335987,2007/08,Jaipur,21-04-2008,League,SR Watson,Sawai Mansingh Stadium,Rajasthan,Punjab,Punjab,bat,Rajasthan,wickets,6,167,20.0,N,standard,Aleem Dar,RB Tiffin
335988,2007/08,Hyderabad,22-04-2008,League,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Delhi,Hyderabad,bat,Delhi,wickets,9,143,20.0,N,standard,IL Howell,AM Saheba
335989,2007/08,Chennai,23-04-2008,League,ML Hayden,"MA Chidambaram Stadium, Chepauk",Chennai,Mumbai,Mumbai,field,Chennai,runs,6,209,20.0,N,standard,DJ Harper,GA Pratapkumar
335990,2007/08,Hyderabad,24-04-2008,League,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Rajasthan,Rajasthan,field,Rajasthan,wickets,3,215,20.0,N,standard,Asad Rauf,MR Benson


In [ ]:
df_ipl.columns

Index(['season', 'city', 'date', 'match_type', 'player_of_match', 'venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'target_runs', 'target_overs', 'super_over', 'method',
       'umpire1', 'umpire2'],
      dtype='object')

In [ ]:
df_ipl.tail(n = 4)

,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
id,,,,,,,,,,,,,,,,,,,
1370350,2023,Chennai,23-05-2023,Qualifier 1,RD Gaikwad,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Gujarat,Gujarat,field,Chennai,runs,15,173,20.0,N,standard,AK Chaudhary,CB Gaffaney
1370351,2023,Chennai,24-05-2023,Eliminator,Akash Madhwal,"MA Chidambaram Stadium, Chepauk, Chennai",Mumbai,Lucknow,Mumbai,bat,Mumbai,runs,81,183,20.0,N,standard,BNJ Oxenford,VK Sharma
1370352,2023,Ahmedabad,26-05-2023,Qualifier 2,Shubman Gill,"Narendra Modi Stadium, Ahmedabad",Gujarat,Mumbai,Mumbai,field,Gujarat,runs,62,234,20.0,N,standard,Nitin Menon,RJ Tucker
1370353,2023,Ahmedabad,29-05-2023,Final,DP Conway,"Narendra Modi Stadium, Ahmedabad",Gujarat,Chennai,Chennai,field,Chennai,wickets,5,171,15.0,N,D/L,Nitin Menon,RJ Tucker


In [ ]:
IBM_Stocks = pd.read_excel('IBM_stocks_data.xlsx')

In [ ]:
IBM_Stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3020 entries, 0 to 3019
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   Date    3020 non-null   datetime64[ns]
 1   Open    3019 non-null   float64       
 2   High    3020 non-null   float64       
 3   Low     3019 non-null   float64       
 4   Close   3020 non-null   float64       
 5   Volume  3020 non-null   int64         
 6   Name    3020 non-null   object        
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 165.3+ KB


In [ ]:
IBM_Stocks.describe()

,Date,Open,High,Low,Close,Volume
count,3020,3019.000000,3020.000000,3019.000000,3020.000000,3.020000e+03
mean,2012-01-01 14:54:59.602649088,145.515545,146.681738,144.471597,145.617278,5.773301e+06
min,2006-01-03 00:00:00,72.740000,73.940000,69.500000,71.740000,2.542560e+05
25%,2009-01-01 12:00:00,116.405000,117.765000,115.490000,116.525000,3.622681e+06
50%,2011-12-29 12:00:00,149.610000,150.330000,148.470000,149.315000,4.928852e+06
75%,2014-12-31 12:00:00,178.445000,179.762500,177.330000,178.685000,6.965014e+06
max,2017-12-29 00:00:00,215.380000,215.900000,214.300000,215.800000,3.077428e+07
std,NaN,37.554946,37.613446,37.477641,37.529387,3.192831e+06


In [ ]:
df_internet = pd.read_json('internet_data.json')

In [ ]:
df_internet

,customerID,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,No,Fiber optic,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes
7039,2234-XADUH,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
7040,4801-JZAZL,No phone service,DSL,Yes,No,No,No,No,No
7041,8361-LTMKD,Yes,Fiber optic,No,No,No,No,No,No


In [ ]:
df_internet.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7042
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   customerID        7043 non-null   object
 1   MultipleLines     7043 non-null   object
 2   InternetService   7043 non-null   object
 3   OnlineSecurity    7043 non-null   object
 4   OnlineBackup      7043 non-null   object
 5   DeviceProtection  7043 non-null   object
 6   TechSupport       7043 non-null   object
 7   StreamingTV       7043 non-null   object
 8   StreamingMovies   7043 non-null   object
dtypes: object(9)
memory usage: 550.2+ KB


In [ ]:
df_internet.dtypes

,0
customerID,object
MultipleLines,object
InternetService,object
OnlineSecurity,object
OnlineBackup,object
DeviceProtection,object
TechSupport,object
StreamingTV,object
StreamingMovies,object


In [ ]:
df_internet.size

63387

In [ ]:
df_internet.shape

(7043, 9)

In [ ]:
df_internet.describe()

,customerID,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
count,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,7043,3,3,3,3,3,3,3,3
top,3186-AJIEK,No,Fiber optic,No,No,No,No,No,No
freq,1,3390,3096,3498,3088,3095,3473,2810,2785


In [ ]:
df1 = pd.read_csv('swiggy.csv', delimiter = ';')

In [ ]:
df1

,"ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time"
0,"211,Koramangala,Bangalore,Tandoor Hut,300.0,4...."
1,"221,Koramangala,Bangalore,Tunday Kababi,300.0,..."
2,"246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,..."
3,"248,Indiranagar,Bangalore,New Punjabi Hotel,25..."
4,"249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,""Ra..."
...,...
8675,"464626,Panjarapole Cross Road,Ahmedabad,Malt P..."
8676,"465835,Rohini,Delhi,Jay Mata Ji Home Kitchen,2..."
8677,"465872,Rohini,Delhi,Chinese Kitchen King,150.0..."
8678,"465990,Rohini,Delhi,Shree Ram Paratha Wala,150..."


In [ ]:
df2 = pd.read_csv('swiggy.csv', header = 0)

In [ ]:
df2

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63
...,...,...,...,...,...,...,...,...,...,...
8675,464626,Panjarapole Cross Road,Ahmedabad,Malt Pizza,500.0,2.9,80,Pizzas,Navrangpura,40
8676,465835,Rohini,Delhi,Jay Mata Ji Home Kitchen,200.0,2.9,80,South Indian,Rohini,28
8677,465872,Rohini,Delhi,Chinese Kitchen King,150.0,2.9,80,"Chinese,Snacks,Tandoor",Rohini,58
8678,465990,Rohini,Delhi,Shree Ram Paratha Wala,150.0,2.9,80,"North Indian,Indian,Snacks",Rohini,28


In [ ]:
df3 = pd.read_csv('swiggy.csv', index_col = 'Area')

In [ ]:
df3

,ID,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
Area,,,,,,,,,
Koramangala,211,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
Koramangala,221,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56
Jogupalya,246,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50
Indiranagar,248,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
Indiranagar,249,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63
...,...,...,...,...,...,...,...,...,...
Panjarapole Cross Road,464626,Ahmedabad,Malt Pizza,500.0,2.9,80,Pizzas,Navrangpura,40
Rohini,465835,Delhi,Jay Mata Ji Home Kitchen,200.0,2.9,80,South Indian,Rohini,28
Rohini,465872,Delhi,Chinese Kitchen King,150.0,2.9,80,"Chinese,Snacks,Tandoor",Rohini,58


In [ ]:
df4 = pd.read_csv('swiggy.csv', index_col = ['ID', 'Area'])

In [ ]:
df4

,,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
ID,Area,,,,,,,,
211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56
246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50
248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63
...,...,...,...,...,...,...,...,...,...
464626,Panjarapole Cross Road,Ahmedabad,Malt Pizza,500.0,2.9,80,Pizzas,Navrangpura,40
465835,Rohini,Delhi,Jay Mata Ji Home Kitchen,200.0,2.9,80,South Indian,Rohini,28
465872,Rohini,Delhi,Chinese Kitchen King,150.0,2.9,80,"Chinese,Snacks,Tandoor",Rohini,58


In [ ]:
df5 = pd.read_csv('swiggy.csv', usecols=['ID', 'Area', 'City'])

In [ ]:
df5

,ID,Area,City
0,211,Koramangala,Bangalore
1,221,Koramangala,Bangalore
2,246,Jogupalya,Bangalore
3,248,Indiranagar,Bangalore
4,249,Indiranagar,Bangalore
...,...,...,...
8675,464626,Panjarapole Cross Road,Ahmedabad
8676,465835,Rohini,Delhi
8677,465872,Rohini,Delhi
8678,465990,Rohini,Delhi


In [ ]:
df6 = pd.read_csv('swiggy.csv', nrows= 6)

In [ ]:
df6

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63
5,254,Indiranagar,Bangalore,Treat,800.0,4.5,100,"Mughlai,North Indian",100 Feet Road,56


In [ ]:
df7 = pd.read_csv('swiggy.csv', skiprows = 500)

In [ ]:
df7

,20510,Machuabazar,Kolkata,Mushroom,500.0,4.4,50,"Indian,Chinese,Tandoor",Oposite Hedua Park,44
0,20513,Shobhabazar,Kolkata,Fusion,500.0,4.6,100,"Indian,Chinese,Tandoor",Near Star Theatre,44
1,20514,Shobhabazar,Kolkata,Lebanese Junction - Steak House,350.0,4.4,500,"Lebanese,Continental",Beside Star Theatre,50
2,20526,Sector 3 Rohini,Delhi,Sahni Fish Corner,700.0,4.2,50,Indian,Sector-8,33
3,20568,Bibwewadi,Pune,Koffee Villa,200.0,2.9,80,"Pizzas,Italian,Pastas",Lake Town Road,72
4,20570,Kondhwa,Pune,Tahari House,200.0,4.4,100,North Indian,Kondhwa,62
...,...,...,...,...,...,...,...,...,...,...
8175,464626,Panjarapole Cross Road,Ahmedabad,Malt Pizza,500.0,2.9,80,Pizzas,Navrangpura,40
8176,465835,Rohini,Delhi,Jay Mata Ji Home Kitchen,200.0,2.9,80,South Indian,Rohini,28
8177,465872,Rohini,Delhi,Chinese Kitchen King,150.0,2.9,80,"Chinese,Snacks,Tandoor",Rohini,58
8178,465990,Rohini,Delhi,Shree Ram Paratha Wala,150.0,2.9,80,"North Indian,Indian,Snacks",Rohini,28


In [ ]:
df8 = pd.read_csv('swiggy.csv', skiprows = range(1,500))

In [ ]:
df8

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,20510,Machuabazar,Kolkata,Mushroom,500.0,4.4,50,"Indian,Chinese,Tandoor",Oposite Hedua Park,44
1,20513,Shobhabazar,Kolkata,Fusion,500.0,4.6,100,"Indian,Chinese,Tandoor",Near Star Theatre,44
2,20514,Shobhabazar,Kolkata,Lebanese Junction - Steak House,350.0,4.4,500,"Lebanese,Continental",Beside Star Theatre,50
3,20526,Sector 3 Rohini,Delhi,Sahni Fish Corner,700.0,4.2,50,Indian,Sector-8,33
4,20568,Bibwewadi,Pune,Koffee Villa,200.0,2.9,80,"Pizzas,Italian,Pastas",Lake Town Road,72
...,...,...,...,...,...,...,...,...,...,...
8176,464626,Panjarapole Cross Road,Ahmedabad,Malt Pizza,500.0,2.9,80,Pizzas,Navrangpura,40
8177,465835,Rohini,Delhi,Jay Mata Ji Home Kitchen,200.0,2.9,80,South Indian,Rohini,28
8178,465872,Rohini,Delhi,Chinese Kitchen King,150.0,2.9,80,"Chinese,Snacks,Tandoor",Rohini,58
8179,465990,Rohini,Delhi,Shree Ram Paratha Wala,150.0,2.9,80,"North Indian,Indian,Snacks",Rohini,28


In [ ]:
df = pd.read_csv('matches_data.csv')
df

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bengaluru,18-04-2008,League,BB McCullum,M Chinnaswamy Stadium,Bengaluru,Kolkata,Bengaluru,field,Kolkata,runs,140,223,20.0,N,standard,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,19-04-2008,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Punjab,Chennai,Chennai,bat,Chennai,runs,33,241,20.0,N,standard,MR Benson,SL Shastri
2,335984,2007/08,Delhi,19-04-2008,League,MF Maharoof,Feroz Shah Kotla,Delhi,Rajasthan,Rajasthan,bat,Delhi,wickets,9,130,20.0,N,standard,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,20-04-2008,League,MV Boucher,Wankhede Stadium,Mumbai,Bengaluru,Mumbai,bat,Bengaluru,wickets,5,166,20.0,N,standard,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,20-04-2008,League,DJ Hussey,Eden Gardens,Kolkata,Hyderabad,Hyderabad,bat,Kolkata,wickets,5,111,20.0,N,standard,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,1359544,2023,Bengaluru,21-05-2023,League,Shubman Gill,"M Chinnaswamy Stadium, Bengaluru",Bengaluru,Gujarat,Gujarat,field,Gujarat,wickets,6,198,20.0,N,standard,Nitin Menon,VK Sharma
1015,1370350,2023,Chennai,23-05-2023,Qualifier 1,RD Gaikwad,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Gujarat,Gujarat,field,Chennai,runs,15,173,20.0,N,standard,AK Chaudhary,CB Gaffaney
1016,1370351,2023,Chennai,24-05-2023,Eliminator,Akash Madhwal,"MA Chidambaram Stadium, Chepauk, Chennai",Mumbai,Lucknow,Mumbai,bat,Mumbai,runs,81,183,20.0,N,standard,BNJ Oxenford,VK Sharma
1017,1370352,2023,Ahmedabad,26-05-2023,Qualifier 2,Shubman Gill,"Narendra Modi Stadium, Ahmedabad",Gujarat,Mumbai,Mumbai,field,Gujarat,runs,62,234,20.0,N,standard,Nitin Menon,RJ Tucker


In [ ]:
df.iloc[0]

,0
id,335982
season,2007/08
city,Bengaluru
date,18-04-2008
match_type,League
player_of_match,BB McCullum
venue,M Chinnaswamy Stadium
team1,Bengaluru
team2,Kolkata
toss_winner,Bengaluru


In [ ]:
df.iloc[0,:]

,0
id,335982
season,2007/08
city,Bengaluru
date,18-04-2008
match_type,League
player_of_match,BB McCullum
venue,M Chinnaswamy Stadium
team1,Bengaluru
team2,Kolkata
toss_winner,Bengaluru


In [ ]:
df.iloc[:,0]

,id
0,335982
1,335983
2,335984
3,335985
4,335986
...,...
1014,1359544
1015,1370350
1016,1370351
1017,1370352


In [ ]:
df.iloc[0,0]

np.int64(335982)

In [ ]:
df.iloc[:2, 5]

,player_of_match
0,BB McCullum
1,MEK Hussey


In [ ]:
df.loc[0, 'winner']

'Kolkata'

In [ ]:
df.loc[df.index == 0, 'winner']

,winner
0,Kolkata


In [ ]:
df.loc[
    (df['target_runs'] >= 200 ) & (df['result_margin'] <= 10),
    ['date', 'team1', 'team2', 'target_runs', 'result_margin']
]

,date,team1,team2,target_runs,result_margin
7,23-04-2008,Chennai,Mumbai,209,6
8,24-04-2008,Hyderabad,Rajasthan,215,3
48,24-05-2008,Chennai,Rajasthan,212,10
116,13-03-2010,Mumbai,Rajasthan,213,4
121,16-03-2010,Bengaluru,Punjab,204,8
148,04-04-2010,Kolkata,Punjab,201,8
259,12-04-2012,Chennai,Bengaluru,206,5
399,18-04-2014,Chennai,Punjab,206,6
435,14-05-2014,Hyderabad,Punjab,206,6
456,01-06-2014,Kolkata,Punjab,200,3


In [ ]:
df.iloc[[1, 10, 100, 1000], [0, 1, 4, 5, 6]]

,id,season,match_type,player_of_match,venue
1,335983,2007/08,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali"
10,335992,2007/08,League,SR Watson,M Chinnaswamy Stadium
100,392225,2009,League,SK Warne,Kingsmead
1000,1359530,2023,League,YBK Jaiswal,"Eden Gardens, Kolkata"


In [ ]:
import numpy as np
data1 = {
    'Name': ['Ashok', 'Bob', 'Chandni', 'Dawood', 'Esha'],
    'Age': [25, 30, 18, 22, 30],
    'City': ['Mumbai', 'Kolkata', 'Delhi', 'Bengaluru', 'Agra'],
    'Income June': [30000, 40000, 50000, 60000, np.nan],
    'Income July': [30500, 40000, 50000, np.nan, 70000]
}

df1 = pd.DataFrame(data1)

In [ ]:
df1

,Name,Age,City,Income June,Income July
0,Ashok,25,Mumbai,30000.0,30500.0
1,Bob,30,Kolkata,40000.0,40000.0
2,Chandni,18,Delhi,50000.0,50000.0
3,Dawood,22,Bengaluru,60000.0,NaN
4,Esha,30,Agra,NaN,70000.0


In [ ]:
df1['Tax on income'] = 0.1 * (df1['Income June'] + (df1['Income July']))
df1['Tax on income']

,Tax on income
0,6050.0
1,8000.0
2,10000.0
3,NaN
4,NaN


In [ ]:
df1['Tax on Income'] = 0.1 * (df1['Income June'].add(df1['Income July'], fill_value = 0))

In [ ]:
df1['Tax on Income']

,Tax on Income
0,6050.0
1,8000.0
2,10000.0
3,6000.0
4,7000.0


In [ ]:
df1['Income June'].sum()

np.float64(180000.0)

In [ ]:
df1['Income June'].mean()

np.float64(45000.0)

In [ ]:
df1['Age'].sort_values()

,Age
2,18
3,22
0,25
1,30
4,30


In [ ]:
df1['Tax in Dollars'] = df1['Tax on Income'].apply(lambda x: x/84)

In [ ]:
df1['Tax in Dollars']

,Tax in Dollars
0,72.023810
1,95.238095
2,119.047619
3,71.428571
4,83.333333


In [ ]:
df1['Tax Statement'] = df1.apply(lambda row: f"{row['Name']}, aged {row['Age']}, owes a tax of ${row['Tax in Dollars']:.2f}.", axis = 1)

In [ ]:
df1['Tax Statement']

,Tax Statement
0,"Ashok, aged 25, owes a tax of $72.02."
1,"Bob, aged 30, owes a tax of $95.24."
2,"Chandni, aged 18, owes a tax of $119.05."
3,"Dawood, aged 22, owes a tax of $71.43."
4,"Esha, aged 30, owes a tax of $83.33."


In [ ]:
df1['Income June + July'] = (df1['Income June'].add(df1['Income July'], fill_value = 0))

In [ ]:
df2 = df1.loc[df1['Age'] > 20, ['Name', 'City', 'Income June + July']].sort_values('Income June + July').reset_index(drop = True)

In [ ]:
df2

,Name,City,Income June + July
0,Dawood,Bengaluru,60000.0
1,Ashok,Mumbai,60500.0
2,Esha,Agra,70000.0
3,Bob,Kolkata,80000.0


In [ ]:
import pandas as pd


In [ ]:
df_volumes = pd.read_csv('GOOGL_volume.csv')
df_prices = pd.read_csv('GOOGL_prices.csv')

In [ ]:
df_volumes.head()

,Date,Volume
0,1/3/2006,13137450
1,1/4/2006,15292353
2,1/5/2006,10815661
3,1/9/2006,12795837
4,1/10/2006,9104719


In [ ]:
df_prices.head()

,Date,Open,High,Low,Close
0,1/3/2006,211.47,218.05,209.32,217.83
1,1/4/2006,222.17,224.70,220.09,222.84
2,1/5/2006,223.22,226.00,220.97,225.85
3,1/6/2006,228.66,235.49,226.85,233.06
4,1/9/2006,233.44,236.94,230.70,233.68


In [ ]:
df_inner_join = pd.merge(df_volumes, df_prices, on = 'Date', how = 'inner')
df_inner_join

,Date,Volume,Open,High,Low,Close
0,1/3/2006,13137450,211.47,218.05,209.32,217.83
1,1/4/2006,15292353,222.17,224.70,220.09,222.84
2,1/5/2006,10815661,223.22,226.00,220.97,225.85
3,1/9/2006,12795837,233.44,236.94,230.70,233.68


In [ ]:
df_outer_join = pd.merge(df_volumes, df_prices, on = 'Date', how = 'outer')
df_outer_join

,Date,Volume,Open,High,Low,Close
0,1/10/2006,9104719.0,NaN,NaN,NaN,NaN
1,1/3/2006,13137450.0,211.47,218.05,209.32,217.83
2,1/4/2006,15292353.0,222.17,224.70,220.09,222.84
3,1/5/2006,10815661.0,223.22,226.00,220.97,225.85
4,1/6/2006,NaN,228.66,235.49,226.85,233.06
5,1/9/2006,12795837.0,233.44,236.94,230.70,233.68


In [ ]:
df_left_join = pd.merge(df_volumes, df_prices, on = 'Date', how = 'left')
df_left_join

,Date,Volume,Open,High,Low,Close
0,1/3/2006,13137450,211.47,218.05,209.32,217.83
1,1/4/2006,15292353,222.17,224.70,220.09,222.84
2,1/5/2006,10815661,223.22,226.00,220.97,225.85
3,1/9/2006,12795837,233.44,236.94,230.70,233.68
4,1/10/2006,9104719,NaN,NaN,NaN,NaN


In [ ]:
df_right_join = pd.merge(df_volumes, df_prices, on = 'Date', how = 'right')
df_right_join

,Date,Volume,Open,High,Low,Close
0,1/3/2006,13137450.0,211.47,218.05,209.32,217.83
1,1/4/2006,15292353.0,222.17,224.70,220.09,222.84
2,1/5/2006,10815661.0,223.22,226.00,220.97,225.85
3,1/6/2006,NaN,228.66,235.49,226.85,233.06
4,1/9/2006,12795837.0,233.44,236.94,230.70,233.68


In [ ]:
df_cross_join = pd.merge(df_volumes, df_prices, how ='cross')
df_cross_join

,Date_x,Volume,Date_y,Open,High,Low,Close
0,1/3/2006,13137450,1/3/2006,211.47,218.05,209.32,217.83
1,1/3/2006,13137450,1/4/2006,222.17,224.70,220.09,222.84
2,1/3/2006,13137450,1/5/2006,223.22,226.00,220.97,225.85
3,1/3/2006,13137450,1/6/2006,228.66,235.49,226.85,233.06
4,1/3/2006,13137450,1/9/2006,233.44,236.94,230.70,233.68
5,1/4/2006,15292353,1/3/2006,211.47,218.05,209.32,217.83
6,1/4/2006,15292353,1/4/2006,222.17,224.70,220.09,222.84
7,1/4/2006,15292353,1/5/2006,223.22,226.00,220.97,225.85
8,1/4/2006,15292353,1/6/2006,228.66,235.49,226.85,233.06
9,1/4/2006,15292353,1/9/2006,233.44,236.94,230.70,233.68


In [ ]:
df_concat_rows = pd.concat([df_volumes, df_prices], axis = 0)

In [ ]:
df_concat_rows

,Date,Volume,Open,High,Low,Close
0,1/3/2006,13137450.0,NaN,NaN,NaN,NaN
1,1/4/2006,15292353.0,NaN,NaN,NaN,NaN
2,1/5/2006,10815661.0,NaN,NaN,NaN,NaN
3,1/9/2006,12795837.0,NaN,NaN,NaN,NaN
4,1/10/2006,9104719.0,NaN,NaN,NaN,NaN
0,1/3/2006,NaN,211.47,218.05,209.32,217.83
1,1/4/2006,NaN,222.17,224.70,220.09,222.84
2,1/5/2006,NaN,223.22,226.00,220.97,225.85
3,1/6/2006,NaN,228.66,235.49,226.85,233.06
4,1/9/2006,NaN,233.44,236.94,230.70,233.68


In [ ]:
df_concat_cols = pd.concat([df_volumes, df_prices], axis = 1)

In [ ]:
df_concat_cols

,Date,Volume,Date,Open,High,Low,Close
0,1/3/2006,13137450,1/3/2006,211.47,218.05,209.32,217.83
1,1/4/2006,15292353,1/4/2006,222.17,224.70,220.09,222.84
2,1/5/2006,10815661,1/5/2006,223.22,226.00,220.97,225.85
3,1/9/2006,12795837,1/6/2006,228.66,235.49,226.85,233.06
4,1/10/2006,9104719,1/9/2006,233.44,236.94,230.70,233.68


In [ ]:
data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Finance', 'Finance', 'Finance'],
    'Product': ['ChatBot', 'Autoflagger', 'ChatBot', 'Autoflagger', 'ChatBot', 'Autoflagger', 'Autoflagger'],
    'Employee': ['Ashok', 'Bob', 'Chandni', 'Dawood', 'Esha', 'Falak', 'Girish'],
    'Salary': [50000, 55000, 60000, 65000, 70000, 72000, 80000],
    'Bonus': [5000, 6000, 7000, 8000, 9000, 9500, 10000]
}

df = pd.DataFrame(data)


In [ ]:
df

,Department,Product,Employee,Salary,Bonus
0,HR,ChatBot,Ashok,50000,5000
1,HR,Autoflagger,Bob,55000,6000
2,IT,ChatBot,Chandni,60000,7000
3,IT,Autoflagger,Dawood,65000,8000
4,Finance,ChatBot,Esha,70000,9000
5,Finance,Autoflagger,Falak,72000,9500
6,Finance,Autoflagger,Girish,80000,10000


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Department  7 non-null      object
 1   Product     7 non-null      object
 2   Employee    7 non-null      object
 3   Salary      7 non-null      int64 
 4   Bonus       7 non-null      int64 
dtypes: int64(2), object(3)
memory usage: 412.0+ bytes


In [ ]:
import numpy as np
department_sum = df.groupby('Department').sum()
department_sum

,Product,Employee,Salary,Bonus
Department,,,,
Finance,ChatBotAutoflaggerAutoflagger,EshaFalakGirish,222000,28500
HR,ChatBotAutoflagger,AshokBob,105000,11000
IT,ChatBotAutoflagger,ChandniDawood,125000,15000


In [ ]:
department_count = df.groupby('Department').count()
department_count

,Product,Employee,Salary,Bonus
Department,,,,
Finance,3,3,3,3
HR,2,2,2,2
IT,2,2,2,2


In [ ]:
df_pivoted = df.pivot(index = 'Department', columns = 'Employee', values = 'Salary')
df_pivoted

Employee,Ashok,Bob,Chandni,Dawood,Esha,Falak,Girish
Department,,,,,,,
Finance,NaN,NaN,NaN,NaN,70000.0,72000.0,80000.0
HR,50000.0,55000.0,NaN,NaN,NaN,NaN,NaN
IT,NaN,NaN,60000.0,65000.0,NaN,NaN,NaN
